-- Location Detection System Migration
-- Enhanced geographic threat analysis and unusual location monitoring

-- User location history table for tracking access patterns
CREATE TABLE IF NOT EXISTS user_location_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  ip_address INET NOT NULL,
  country VARCHAR(100),
  country_code VARCHAR(2),
  region VARCHAR(100),
  city VARCHAR(100),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  timezone VARCHAR(50),
  isp VARCHAR(255),
  organization VARCHAR(255),
  asn VARCHAR(50),
  is_proxy BOOLEAN DEFAULT false,
  is_vpn BOOLEAN DEFAULT false,
  is_tor BOOLEAN DEFAULT false,
  is_hosting BOOLEAN DEFAULT false,
  is_malicious BOOLEAN DEFAULT false,
  accuracy INTEGER,
  access_count INTEGER DEFAULT 1,
  first_access TIMESTAMP DEFAULT NOW(),
  last_access TIMESTAMP DEFAULT NOW(),
  risk_score INTEGER DEFAULT 0,
  verified BOOLEAN DEFAULT false,
  flagged BOOLEAN DEFAULT false,
  flag_reason TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Location alerts table for security notifications
CREATE TABLE IF NOT EXISTS location_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  ip_address INET NOT NULL,
  alert_type VARCHAR(50) NOT NULL CHECK (alert_type IN (
    'new_country', 'new_city', 'impossible_travel', 
    'proxy_detected', 'malicious_ip', 'high_risk_region'
  )),
  severity VARCHAR(20) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  description TEXT NOT NULL,
  location_data JSONB,
  metadata JSONB,
  acknowledged BOOLEAN DEFAULT false,
  acknowledged_by VARCHAR(255),
  acknowledged_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- IP geolocation cache for performance optimization
CREATE TABLE IF NOT EXISTS ip_geolocation_cache (
  ip_address INET PRIMARY KEY,
  location_data JSONB NOT NULL,
  provider VARCHAR(50) NOT NULL,
  last_updated TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL
);

-- Malicious IP tracking for threat intelligence
CREATE TABLE IF NOT EXISTS malicious_ips (
  ip_address INET PRIMARY KEY,
  threat_type VARCHAR(100) NOT NULL,
  confidence INTEGER NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  source VARCHAR(100) NOT NULL,
  description TEXT,
  first_seen TIMESTAMP DEFAULT NOW(),
  last_seen TIMESTAMP DEFAULT NOW(),
  active BOOLEAN DEFAULT true
);

-- Performance indexes for location detection queries
CREATE INDEX IF NOT EXISTS idx_user_location_history_user_id ON user_location_history(user_id);
CREATE INDEX IF NOT EXISTS idx_user_location_history_ip ON user_location_history(ip_address);
CREATE INDEX IF NOT EXISTS idx_user_location_history_last_access ON user_location_history(last_access);
CREATE INDEX IF NOT EXISTS idx_user_location_history_country ON user_location_history(country_code);
CREATE INDEX IF NOT EXISTS idx_user_location_history_flagged ON user_location_history(flagged);

CREATE INDEX IF NOT EXISTS idx_location_alerts_user_id ON location_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_location_alerts_severity ON location_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_location_alerts_acknowledged ON location_alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_location_alerts_type ON location_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_location_alerts_created ON location_alerts(created_at);

CREATE INDEX IF NOT EXISTS idx_ip_geolocation_cache_expires ON ip_geolocation_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_ip_geolocation_cache_provider ON ip_geolocation_cache(provider);

CREATE INDEX IF NOT EXISTS idx_malicious_ips_active ON malicious_ips(active);
CREATE INDEX IF NOT EXISTS idx_malicious_ips_threat_type ON malicious_ips(threat_type);
CREATE INDEX IF NOT EXISTS idx_malicious_ips_confidence ON malicious_ips(confidence);

-- Composite indexes for complex queries
CREATE INDEX IF NOT EXISTS idx_location_history_user_country ON user_location_history(user_id, country_code);
CREATE INDEX IF NOT EXISTS idx_location_history_user_city ON user_location_history(user_id, city, country_code);
CREATE INDEX IF NOT EXISTS idx_location_alerts_user_severity ON location_alerts(user_id, severity);

-- Comments for documentation
COMMENT ON TABLE user_location_history IS 'Tracks user login locations and access patterns for security analysis';
COMMENT ON TABLE location_alerts IS 'Security alerts generated by location-based threat detection';
COMMENT ON TABLE ip_geolocation_cache IS 'Cache for IP geolocation data to reduce API calls';
COMMENT ON TABLE malicious_ips IS 'Known malicious IP addresses from threat intelligence feeds';

COMMENT ON COLUMN user_location_history.risk_score IS 'Calculated risk score for this location (0-100)';
COMMENT ON COLUMN user_location_history.access_count IS 'Number of times user accessed from this location';
COMMENT ON COLUMN user_location_history.verified IS 'Whether this location has been verified by user';
COMMENT ON COLUMN user_location_history.flagged IS 'Whether this location has been flagged for review';

COMMENT ON COLUMN location_alerts.alert_type IS 'Type of location-based security alert';
COMMENT ON COLUMN location_alerts.metadata IS 'Additional context data for the alert (travel analysis, etc.)';
COMMENT ON COLUMN malicious_ips.confidence IS 'Confidence level of threat intelligence (0-100)';