[build]
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  NPM_FLAGS = "--prefix=client"
  NODE_VERSION = "18.12.1"

[dev]
  command = "pnpm --filter client dev"
  port = 3000
  targetPort = 3000
