-- Epic 17 Export Functionality Database Schema
-- Task: E17-1753114396845-6C7602 - Implement export functionality
-- 
-- Creates comprehensive export infrastructure for Epic 17 API Management System
-- including export request management, format support, scheduling, compliance tracking,
-- secure file handling, and comprehensive audit trails for data export operations.

-- Export requests tracking and management
CREATE TABLE IF NOT EXISTS epic17_export_requests (
    id SERIAL PRIMARY KEY,
    export_id UUID UNIQUE NOT NULL,
    export_type VARCHAR(50) NOT NULL, -- api_keys, users, permissions, audit_logs, usage_analytics, compliance_report, security_report, custom_query, full_backup, incremental_backup
    export_format VARCHAR(20) NOT NULL, -- json, csv, xml, excel, pdf, yaml, tsv, parquet
    status VARCHAR(20) DEFAULT 'pending', -- pending, queued, preparing, exporting, processing, compressing, encrypting, completed, failed, cancelled, expired
    
    -- Request metadata
    title VARCHAR(255) NOT NULL,
    description TEXT,
    requested_by VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Configuration
    data_filters JSONB NOT NULL, -- Filtering criteria for data selection
    custom_query TEXT, -- Custom SQL query for advanced exports
    include_metadata BOOLEAN DEFAULT TRUE,
    include_sensitive_data BOOLEAN DEFAULT FALSE,
    
    -- Output configuration
    output_options JSONB NOT NULL, -- Format-specific output options
    compression_options JSONB DEFAULT '{}'::jsonb,
    encryption_options JSONB DEFAULT '{}'::jsonb,
    processing_options JSONB NOT NULL,
    
    -- Scheduling configuration
    scheduling_options JSONB DEFAULT '{}'::jsonb,
    is_scheduled BOOLEAN DEFAULT FALSE,
    next_run_at TIMESTAMP WITH TIME ZONE,
    
    -- Progress tracking
    total_records INTEGER DEFAULT 0,
    processed_records INTEGER DEFAULT 0,
    estimated_completion TIMESTAMP WITH TIME ZONE,
    progress_percentage INTEGER DEFAULT 0,
    
    -- Execution tracking
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    execution_time INTEGER DEFAULT 0, -- milliseconds
    file_size BIGINT DEFAULT 0, -- bytes
    
    -- Error and status tracking
    errors JSONB DEFAULT '[]'::jsonb, -- Array of error objects
    warnings JSONB DEFAULT '[]'::jsonb, -- Array of warning objects
    
    -- Compliance and audit
    compliance_info JSONB NOT NULL, -- Compliance and regulatory information
    audit_trail JSONB DEFAULT '[]'::jsonb, -- Detailed audit trail
    
    -- Lifecycle management
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Indexes
    INDEX idx_epic17_exports_export_id (export_id),
    INDEX idx_epic17_exports_type (export_type),
    INDEX idx_epic17_exports_format (export_format),
    INDEX idx_epic17_exports_status (status),
    INDEX idx_epic17_exports_requested_by (requested_by),
    INDEX idx_epic17_exports_requested_at (requested_at),
    INDEX idx_epic17_exports_scheduled (is_scheduled, next_run_at),
    INDEX idx_epic17_exports_expires_at (expires_at),
    INDEX idx_epic17_exports_active (status) WHERE status IN ('pending', 'queued', 'preparing', 'exporting', 'processing'),
    INDEX idx_epic17_exports_recent (requested_at DESC, export_type) WHERE requested_at >= NOW() - INTERVAL '30 days'
);

-- Output files generated by export operations
CREATE TABLE IF NOT EXISTS epic17_export_output_files (
    id SERIAL PRIMARY KEY,
    file_id UUID UNIQUE NOT NULL,
    export_id UUID NOT NULL,
    
    -- File identification
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    export_format VARCHAR(20) NOT NULL,
    
    -- File metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    checksum VARCHAR(128) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    encoding VARCHAR(20),
    
    -- Security and processing
    encrypted BOOLEAN DEFAULT FALSE,
    compressed BOOLEAN DEFAULT FALSE,
    access_token VARCHAR(255), -- For secure downloads
    
    -- Content information
    record_count INTEGER DEFAULT 0,
    columns_info JSONB DEFAULT '[]'::jsonb, -- Column names and types
    schema_info JSONB DEFAULT '{}'::jsonb, -- Schema information
    
    -- Access tracking
    download_count INTEGER DEFAULT 0,
    last_downloaded_at TIMESTAMP WITH TIME ZONE,
    last_downloaded_by VARCHAR(255),
    
    -- File lifecycle
    status VARCHAR(20) DEFAULT 'available', -- available, archived, deleted, corrupted
    archived_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    
    -- Indexes
    INDEX idx_epic17_export_files_file_id (file_id),
    INDEX idx_epic17_export_files_export_id (export_id),
    INDEX idx_epic17_export_files_file_name (file_name),
    INDEX idx_epic17_export_files_created_at (created_at),
    INDEX idx_epic17_export_files_status (status),
    INDEX idx_epic17_export_files_checksum (checksum),
    INDEX idx_epic17_export_files_download_tracking (download_count, last_downloaded_at),
    
    FOREIGN KEY (export_id) REFERENCES epic17_export_requests(export_id) ON DELETE CASCADE
);

-- Scheduled export management and automation
CREATE TABLE IF NOT EXISTS epic17_scheduled_exports (
    id SERIAL PRIMARY KEY,
    schedule_id UUID UNIQUE NOT NULL,
    schedule_name VARCHAR(255) NOT NULL,
    description TEXT,
    
    -- Schedule configuration
    export_template JSONB NOT NULL, -- Template for creating export requests
    cron_expression VARCHAR(100) NOT NULL,
    timezone VARCHAR(50) DEFAULT 'UTC',
    
    -- Schedule status and control
    enabled BOOLEAN DEFAULT TRUE,
    last_run_at TIMESTAMP WITH TIME ZONE,
    next_run_at TIMESTAMP WITH TIME ZONE,
    run_count INTEGER DEFAULT 0,
    
    -- Execution limits and controls
    max_concurrent_runs INTEGER DEFAULT 1,
    retry_attempts INTEGER DEFAULT 3,
    retry_delay_minutes INTEGER DEFAULT 30,
    
    -- Success/failure tracking
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_failure_at TIMESTAMP WITH TIME ZONE,
    last_error_message TEXT,
    
    -- Dependencies and conditions
    dependencies JSONB DEFAULT '[]'::jsonb, -- Array of dependency schedule IDs
    execution_conditions JSONB DEFAULT '{}'::jsonb, -- Conditions that must be met
    
    -- Lifecycle management
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    
    -- Notification settings
    notification_settings JSONB DEFAULT '{}'::jsonb,
    
    -- Indexes
    INDEX idx_epic17_scheduled_exports_schedule_id (schedule_id),
    INDEX idx_epic17_scheduled_exports_enabled (enabled),
    INDEX idx_epic17_scheduled_exports_next_run (next_run_at),
    INDEX idx_epic17_scheduled_exports_created_by (created_by),
    INDEX idx_epic17_scheduled_exports_success_rate (success_count, failure_count),
    INDEX idx_epic17_scheduled_exports_active (enabled, next_run_at) WHERE enabled = TRUE AND next_run_at IS NOT NULL
);

-- Export execution history for scheduled and manual exports
CREATE TABLE IF NOT EXISTS epic17_export_execution_history (
    id SERIAL PRIMARY KEY,
    execution_id UUID UNIQUE NOT NULL,
    export_id UUID,
    schedule_id UUID,
    
    -- Execution details
    execution_type VARCHAR(20) NOT NULL, -- manual, scheduled, triggered
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    execution_duration INTEGER, -- milliseconds
    
    -- Execution status
    status VARCHAR(20) NOT NULL, -- running, completed, failed, cancelled
    result_summary JSONB DEFAULT '{}'::jsonb,
    
    -- Performance metrics
    records_processed INTEGER DEFAULT 0,
    files_generated INTEGER DEFAULT 0,
    total_file_size BIGINT DEFAULT 0,
    peak_memory_usage INTEGER, -- MB
    cpu_usage_avg DECIMAL(5,2), -- percentage
    
    -- Error tracking
    error_count INTEGER DEFAULT 0,
    warning_count INTEGER DEFAULT 0,
    error_details JSONB DEFAULT '[]'::jsonb,
    
    -- Resource utilization
    database_queries_count INTEGER DEFAULT 0,
    cache_hit_ratio DECIMAL(5,2) DEFAULT 0,
    network_bytes_sent BIGINT DEFAULT 0,
    
    -- Context information
    triggered_by VARCHAR(255),
    trigger_context JSONB DEFAULT '{}'::jsonb,
    execution_environment JSONB DEFAULT '{}'::jsonb,
    
    -- Indexes
    INDEX idx_epic17_export_history_execution_id (execution_id),
    INDEX idx_epic17_export_history_export_id (export_id),
    INDEX idx_epic17_export_history_schedule_id (schedule_id),
    INDEX idx_epic17_export_history_started_at (started_at),
    INDEX idx_epic17_export_history_status (status),
    INDEX idx_epic17_export_history_execution_type (execution_type),
    INDEX idx_epic17_export_history_performance (execution_duration, records_processed),
    INDEX idx_epic17_export_history_recent (started_at DESC, status) WHERE started_at >= NOW() - INTERVAL '7 days',
    
    FOREIGN KEY (export_id) REFERENCES epic17_export_requests(export_id) ON DELETE CASCADE,
    FOREIGN KEY (schedule_id) REFERENCES epic17_scheduled_exports(schedule_id) ON DELETE CASCADE
);

-- Export templates for common export configurations
CREATE TABLE IF NOT EXISTS epic17_export_templates (
    id SERIAL PRIMARY KEY,
    template_id UUID UNIQUE NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    description TEXT,
    
    -- Template configuration
    export_type VARCHAR(50) NOT NULL,
    export_format VARCHAR(20) NOT NULL,
    template_config JSONB NOT NULL, -- Complete export configuration template
    
    -- Template categorization
    category VARCHAR(50), -- compliance, reporting, backup, analytics, security
    use_case VARCHAR(100), -- Specific use case this template serves
    complexity_level VARCHAR(20) DEFAULT 'medium', -- simple, medium, complex
    
    -- Usage tracking
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMP WITH TIME ZONE,
    success_rate DECIMAL(5,2) DEFAULT 0,
    
    -- Template management
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    is_system_template BOOLEAN DEFAULT FALSE,
    
    -- Access control
    allowed_roles JSONB DEFAULT '[]'::jsonb,
    allowed_users JSONB DEFAULT '[]'::jsonb,
    visibility VARCHAR(20) DEFAULT 'private', -- private, shared, public
    
    -- Validation and quality
    validation_rules JSONB DEFAULT '[]'::jsonb,
    quality_score DECIMAL(5,2) DEFAULT 0,
    
    -- Indexes
    INDEX idx_epic17_export_templates_template_id (template_id),
    INDEX idx_epic17_export_templates_name (template_name),
    INDEX idx_epic17_export_templates_export_type (export_type),
    INDEX idx_epic17_export_templates_category (category),
    INDEX idx_epic17_export_templates_is_active (is_active),
    INDEX idx_epic17_export_templates_created_by (created_by),
    INDEX idx_epic17_export_templates_usage (usage_count, success_rate),
    INDEX idx_epic17_export_templates_active_public (is_active, visibility) WHERE is_active = TRUE
);

-- Data redaction rules for export compliance and security
CREATE TABLE IF NOT EXISTS epic17_export_redaction_rules (
    id SERIAL PRIMARY KEY,
    rule_id UUID UNIQUE NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    description TEXT,
    
    -- Rule configuration
    field_name VARCHAR(255) NOT NULL,
    redaction_type VARCHAR(30) NOT NULL, -- mask, remove, hash, anonymize, encrypt, tokenize
    redaction_pattern VARCHAR(500), -- Pattern for matching content to redact
    replacement_value VARCHAR(100), -- Static replacement value
    
    -- Rule conditions
    applies_to_export_types JSONB DEFAULT '[]'::jsonb, -- Array of export types this rule applies to
    applies_to_user_roles JSONB DEFAULT '[]'::jsonb, -- Array of user roles this rule applies to
    conditional_logic TEXT, -- Additional conditional logic for rule application
    
    -- Rule behavior
    priority INTEGER DEFAULT 100,
    enabled BOOLEAN DEFAULT TRUE,
    strict_mode BOOLEAN DEFAULT FALSE, -- If true, export fails if redaction fails
    
    -- Usage and performance tracking
    usage_count INTEGER DEFAULT 0,
    average_processing_time INTEGER DEFAULT 0, -- milliseconds
    last_used_at TIMESTAMP WITH TIME ZONE,
    
    -- Rule management
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Compliance and regulatory
    compliance_requirements JSONB DEFAULT '[]'::jsonb, -- Array of compliance requirements this rule addresses
    regulatory_references JSONB DEFAULT '[]'::jsonb, -- References to regulatory guidelines
    
    -- Quality and validation
    test_cases JSONB DEFAULT '[]'::jsonb, -- Test cases for validating rule behavior
    validation_passed BOOLEAN DEFAULT TRUE,
    last_validated_at TIMESTAMP WITH TIME ZONE,
    
    -- Indexes
    INDEX idx_epic17_redaction_rules_rule_id (rule_id),
    INDEX idx_epic17_redaction_rules_field_name (field_name),
    INDEX idx_epic17_redaction_rules_redaction_type (redaction_type),
    INDEX idx_epic17_redaction_rules_enabled (enabled),
    INDEX idx_epic17_redaction_rules_priority (priority),
    INDEX idx_epic17_redaction_rules_created_by (created_by),
    INDEX idx_epic17_redaction_rules_usage (usage_count, average_processing_time),
    INDEX idx_epic17_redaction_rules_active (enabled, priority) WHERE enabled = TRUE
);

-- Export notifications and alerts management
CREATE TABLE IF NOT EXISTS epic17_export_notifications (
    id SERIAL PRIMARY KEY,
    notification_id UUID UNIQUE NOT NULL,
    export_id UUID,
    schedule_id UUID,
    
    -- Notification details
    notification_type VARCHAR(30) NOT NULL, -- completion, failure, warning, scheduled, large_export
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL, -- info, warning, error, critical
    
    -- Recipient information
    recipients JSONB NOT NULL, -- Array of recipient objects (email, user_id, etc.)
    delivery_channels JSONB DEFAULT '["email"]'::jsonb, -- Array of delivery channels
    
    -- Delivery tracking
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    delivery_status JSONB DEFAULT '{}'::jsonb, -- Status per channel per recipient
    delivery_attempts INTEGER DEFAULT 0,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    
    -- Response tracking
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by VARCHAR(255),
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    
    -- Context and metadata
    context_data JSONB DEFAULT '{}'::jsonb,
    notification_template_id UUID,
    
    -- Lifecycle
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT (NOW() + INTERVAL '7 days'),
    archived BOOLEAN DEFAULT FALSE,
    archived_at TIMESTAMP WITH TIME ZONE,
    
    -- Indexes
    INDEX idx_epic17_export_notifications_notification_id (notification_id),
    INDEX idx_epic17_export_notifications_export_id (export_id),
    INDEX idx_epic17_export_notifications_schedule_id (schedule_id),
    INDEX idx_epic17_export_notifications_type (notification_type),
    INDEX idx_epic17_export_notifications_severity (severity),
    INDEX idx_epic17_export_notifications_sent_at (sent_at),
    INDEX idx_epic17_export_notifications_acknowledged (acknowledged),
    INDEX idx_epic17_export_notifications_expires_at (expires_at),
    INDEX idx_epic17_export_notifications_unacknowledged (acknowledged, severity) WHERE acknowledged = FALSE,
    
    FOREIGN KEY (export_id) REFERENCES epic17_export_requests(export_id) ON DELETE CASCADE,
    FOREIGN KEY (schedule_id) REFERENCES epic17_scheduled_exports(schedule_id) ON DELETE CASCADE
);

-- Export performance metrics and analytics
CREATE TABLE IF NOT EXISTS epic17_export_performance_metrics (
    id SERIAL PRIMARY KEY,
    metric_id UUID UNIQUE NOT NULL,
    measurement_timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    measurement_period VARCHAR(20) NOT NULL, -- real_time, hourly, daily, weekly, monthly
    
    -- Overall system metrics
    total_exports INTEGER DEFAULT 0,
    completed_exports INTEGER DEFAULT 0,
    failed_exports INTEGER DEFAULT 0,
    cancelled_exports INTEGER DEFAULT 0,
    active_exports INTEGER DEFAULT 0,
    
    -- Performance metrics
    average_execution_time INTEGER DEFAULT 0, -- milliseconds
    median_execution_time INTEGER DEFAULT 0, -- milliseconds
    max_execution_time INTEGER DEFAULT 0, -- milliseconds
    average_file_size BIGINT DEFAULT 0, -- bytes
    total_data_exported BIGINT DEFAULT 0, -- bytes
    
    -- Format distribution
    format_distribution JSONB DEFAULT '{}'::jsonb, -- Distribution of export formats
    type_distribution JSONB DEFAULT '{}'::jsonb, -- Distribution of export types
    
    -- Resource utilization
    peak_concurrent_exports INTEGER DEFAULT 0,
    average_memory_usage INTEGER DEFAULT 0, -- MB
    peak_memory_usage INTEGER DEFAULT 0, -- MB
    average_cpu_usage DECIMAL(5,2) DEFAULT 0, -- percentage
    
    -- Error analysis
    error_rate DECIMAL(5,2) DEFAULT 0, -- percentage
    top_error_types JSONB DEFAULT '[]'::jsonb,
    warning_rate DECIMAL(5,2) DEFAULT 0,
    
    -- User activity
    unique_users_count INTEGER DEFAULT 0,
    most_active_user VARCHAR(255),
    user_activity_distribution JSONB DEFAULT '{}'::jsonb,
    
    -- Scheduled exports metrics
    scheduled_exports_count INTEGER DEFAULT 0,
    scheduled_success_rate DECIMAL(5,2) DEFAULT 0,
    scheduled_average_duration INTEGER DEFAULT 0,
    
    -- Quality metrics
    data_quality_score DECIMAL(5,2) DEFAULT 0,
    compliance_score DECIMAL(5,2) DEFAULT 0,
    user_satisfaction_score DECIMAL(5,2) DEFAULT 0,
    
    -- Indexes
    INDEX idx_epic17_export_metrics_metric_id (metric_id),
    INDEX idx_epic17_export_metrics_timestamp (measurement_timestamp),
    INDEX idx_epic17_export_metrics_period (measurement_period),
    INDEX idx_epic17_export_metrics_recent (measurement_timestamp DESC, measurement_period) WHERE measurement_timestamp >= NOW() - INTERVAL '30 days'
);

-- Create comprehensive functions for export management

-- Function to get export request summary
CREATE OR REPLACE FUNCTION get_export_request_summary(
    p_export_id UUID
) RETURNS TABLE(
    export_id UUID,
    export_type VARCHAR(50),
    export_format VARCHAR(20),
    status VARCHAR(20),
    requested_by VARCHAR(255),
    progress_percentage INTEGER,
    total_records INTEGER,
    processed_records INTEGER,
    estimated_completion TIMESTAMP WITH TIME ZONE,
    file_count BIGINT,
    total_file_size BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        e.export_id,
        e.export_type,
        e.export_format,
        e.status,
        e.requested_by,
        e.progress_percentage,
        e.total_records,
        e.processed_records,
        e.estimated_completion,
        COALESCE(f.file_count, 0) as file_count,
        COALESCE(f.total_size, 0) as total_file_size
    FROM epic17_export_requests e
    LEFT JOIN (
        SELECT 
            export_id,
            COUNT(*) as file_count,
            SUM(file_size) as total_size
        FROM epic17_export_output_files 
        WHERE status = 'available'
        GROUP BY export_id
    ) f ON e.export_id = f.export_id
    WHERE e.export_id = p_export_id;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate export performance metrics
CREATE OR REPLACE FUNCTION calculate_export_performance_metrics(
    p_time_window_hours INTEGER DEFAULT 24
) RETURNS TABLE(
    total_exports BIGINT,
    completed_exports BIGINT,
    failed_exports BIGINT,
    success_rate DECIMAL(5,2),
    average_execution_time DECIMAL(10,2),
    total_data_exported BIGINT,
    most_used_format VARCHAR(20),
    most_used_type VARCHAR(50),
    peak_concurrent_exports INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*) as total_exports,
        COUNT(*) FILTER (WHERE status = 'completed') as completed_exports,
        COUNT(*) FILTER (WHERE status = 'failed') as failed_exports,
        CASE 
            WHEN COUNT(*) > 0 THEN 
                (COUNT(*) FILTER (WHERE status = 'completed')::DECIMAL / COUNT(*) * 100)::DECIMAL(5,2)
            ELSE 0::DECIMAL(5,2)
        END as success_rate,
        AVG(execution_time) FILTER (WHERE execution_time > 0) as average_execution_time,
        SUM(file_size) as total_data_exported,
        
        (SELECT export_format 
         FROM epic17_export_requests 
         WHERE requested_at >= NOW() - (p_time_window_hours || ' hours')::INTERVAL
         GROUP BY export_format 
         ORDER BY COUNT(*) DESC 
         LIMIT 1) as most_used_format,
         
        (SELECT export_type 
         FROM epic17_export_requests 
         WHERE requested_at >= NOW() - (p_time_window_hours || ' hours')::INTERVAL
         GROUP BY export_type 
         ORDER BY COUNT(*) DESC 
         LIMIT 1) as most_used_type,
         
        -- This is a simplified calculation for peak concurrent exports
        (SELECT MAX(concurrent_count)
         FROM (
             SELECT 
                 COUNT(*) as concurrent_count
             FROM epic17_export_requests
             WHERE requested_at >= NOW() - (p_time_window_hours || ' hours')::INTERVAL
                 AND status IN ('preparing', 'exporting', 'processing', 'compressing', 'encrypting')
             GROUP BY DATE_TRUNC('hour', requested_at)
         ) subq) as peak_concurrent_exports
         
    FROM epic17_export_requests
    WHERE requested_at >= NOW() - (p_time_window_hours || ' hours')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Function to get scheduled export status
CREATE OR REPLACE FUNCTION get_scheduled_export_status() 
RETURNS TABLE(
    total_schedules BIGINT,
    active_schedules BIGINT,
    overdue_schedules BIGINT,
    successful_runs_today BIGINT,
    failed_runs_today BIGINT,
    next_scheduled_run TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*) as total_schedules,
        COUNT(*) FILTER (WHERE enabled = TRUE) as active_schedules,
        COUNT(*) FILTER (WHERE enabled = TRUE AND next_run_at < NOW()) as overdue_schedules,
        
        (SELECT COUNT(*) 
         FROM epic17_export_execution_history 
         WHERE execution_type = 'scheduled' 
             AND started_at >= CURRENT_DATE 
             AND status = 'completed') as successful_runs_today,
             
        (SELECT COUNT(*) 
         FROM epic17_export_execution_history 
         WHERE execution_type = 'scheduled' 
             AND started_at >= CURRENT_DATE 
             AND status = 'failed') as failed_runs_today,
             
        MIN(next_run_at) FILTER (WHERE enabled = TRUE AND next_run_at > NOW()) as next_scheduled_run
        
    FROM epic17_scheduled_exports;
END;
$$ LANGUAGE plpgsql;

-- Function to cleanup expired export files and requests
CREATE OR REPLACE FUNCTION cleanup_expired_exports() RETURNS INTEGER AS $$
DECLARE
    expired_requests INTEGER := 0;
    expired_files INTEGER := 0;
    total_cleaned INTEGER := 0;
BEGIN
    -- Update expired requests
    UPDATE epic17_export_requests 
    SET status = 'expired', updated_at = NOW()
    WHERE status NOT IN ('completed', 'failed', 'cancelled', 'expired')
        AND expires_at IS NOT NULL 
        AND expires_at <= NOW();
    
    GET DIAGNOSTICS expired_requests = ROW_COUNT;
    
    -- Mark output files as deleted for expired requests
    UPDATE epic17_export_output_files 
    SET status = 'deleted', deleted_at = NOW()
    WHERE export_id IN (
        SELECT export_id 
        FROM epic17_export_requests 
        WHERE status = 'expired'
    ) AND status = 'available';
    
    GET DIAGNOSTICS expired_files = ROW_COUNT;
    
    total_cleaned := expired_requests + expired_files;
    
    -- Log cleanup operation
    INSERT INTO epic17_admin_tool_usage (
        usage_id, tool_name, action, used_by, records_affected, success
    ) VALUES (
        gen_random_uuid(), 'export_service', 'cleanup_expired', 'system', total_cleaned, true
    );
    
    RETURN total_cleaned;
END;
$$ LANGUAGE plpgsql;

-- Function to apply redaction rules to exported data
CREATE OR REPLACE FUNCTION apply_redaction_rules(
    p_data JSONB,
    p_export_type VARCHAR(50),
    p_user_roles VARCHAR[] DEFAULT ARRAY[]::VARCHAR[]
) RETURNS JSONB AS $$
DECLARE
    rule RECORD;
    redacted_data JSONB := p_data;
    field_value TEXT;
BEGIN
    -- Get applicable redaction rules
    FOR rule IN
        SELECT * FROM epic17_export_redaction_rules
        WHERE enabled = TRUE
            AND (
                applies_to_export_types = '[]'::jsonb OR 
                applies_to_export_types ? p_export_type
            )
            AND (
                applies_to_user_roles = '[]'::jsonb OR 
                applies_to_user_roles ?| p_user_roles
            )
        ORDER BY priority ASC
    LOOP
        -- Check if field exists in data
        IF redacted_data ? rule.field_name THEN
            field_value := redacted_data ->> rule.field_name;
            
            -- Apply redaction based on type
            CASE rule.redaction_type
                WHEN 'mask' THEN
                    redacted_data := jsonb_set(
                        redacted_data, 
                        ('{' || rule.field_name || '}')::text[], 
                        to_jsonb(COALESCE(rule.replacement_value, '***MASKED***'))
                    );
                    
                WHEN 'remove' THEN
                    redacted_data := redacted_data - rule.field_name;
                    
                WHEN 'hash' THEN
                    redacted_data := jsonb_set(
                        redacted_data, 
                        ('{' || rule.field_name || '}')::text[], 
                        to_jsonb(encode(digest(field_value, 'sha256'), 'hex'))
                    );
                    
                WHEN 'anonymize' THEN
                    redacted_data := jsonb_set(
                        redacted_data, 
                        ('{' || rule.field_name || '}')::text[], 
                        to_jsonb(COALESCE(rule.replacement_value, 'ANONYMIZED'))
                    );
            END CASE;
            
            -- Update rule usage statistics
            UPDATE epic17_export_redaction_rules
            SET 
                usage_count = usage_count + 1,
                last_used_at = NOW()
            WHERE rule_id = rule.rule_id;
        END IF;
    END LOOP;
    
    RETURN redacted_data;
END;
$$ LANGUAGE plpgsql;

-- Insert default export templates
INSERT INTO epic17_export_templates (
    template_id, template_name, description, export_type, export_format, template_config,
    category, use_case, created_by, is_system_template
) VALUES
(
    gen_random_uuid(),
    'API Keys Compliance Export',
    'Standard export of API keys for compliance reporting',
    'api_keys',
    'excel',
    '{
        "data_filters": {
            "statusFilters": {"includeActive": true, "includeInactive": true},
            "entityFilters": {}
        },
        "output_options": {
            "includeTimestamp": true,
            "excelOptions": {
                "sheetName": "API Keys Report",
                "freezeHeader": true,
                "autoFilter": true
            }
        },
        "processing_options": {
            "enableStreaming": true,
            "chunkSize": 1000
        }
    }',
    'compliance',
    'Regulatory compliance reporting for API key usage',
    'system',
    true
),
(
    gen_random_uuid(),
    'User Activity Report',
    'Comprehensive user activity export for security analysis',
    'audit_logs',
    'csv',
    '{
        "data_filters": {
            "dateRange": {
                "field": "created_at",
                "startDate": "30_days_ago"
            }
        },
        "output_options": {
            "includeTimestamp": true,
            "csvOptions": {
                "delimiter": ",",
                "includeHeaders": true
            }
        },
        "processing_options": {
            "enableStreaming": true,
            "chunkSize": 5000
        }
    }',
    'security',
    'Security analysis and user activity monitoring',
    'system',
    true
),
(
    gen_random_uuid(),
    'Full System Backup',
    'Complete system data backup in JSON format',
    'full_backup',
    'json',
    '{
        "data_filters": {},
        "output_options": {
            "includeTimestamp": true,
            "jsonOptions": {
                "prettyPrint": false,
                "includeSchema": true
            }
        },
        "processing_options": {
            "enableStreaming": true,
            "chunkSize": 500,
            "validateOutput": true
        }
    }',
    'backup',
    'Complete system backup for disaster recovery',
    'system',
    true
),
(
    gen_random_uuid(),
    'Usage Analytics Dashboard Export',
    'Usage analytics data for dashboard reporting',
    'usage_analytics',
    'pdf',
    '{
        "data_filters": {
            "dateRange": {
                "field": "created_at",
                "startDate": "7_days_ago"
            }
        },
        "output_options": {
            "includeTimestamp": true,
            "pdfOptions": {
                "pageSize": "A4",
                "orientation": "landscape",
                "includeCharts": true
            }
        }
    }',
    'analytics',
    'Executive dashboard and analytics reporting',
    'system',
    true
)
ON CONFLICT (template_id) DO NOTHING;

-- Insert default redaction rules
INSERT INTO epic17_export_redaction_rules (
    rule_id, rule_name, field_name, redaction_type, replacement_value,
    applies_to_export_types, created_by, compliance_requirements
) VALUES
(
    gen_random_uuid(),
    'Mask API Key Values',
    'api_key_value',
    'mask',
    '***REDACTED***',
    '["api_keys", "full_backup"]',
    'system',
    '["PCI DSS", "GDPR"]'
),
(
    gen_random_uuid(),
    'Hash User Email Addresses',
    'email',
    'hash',
    NULL,
    '["users", "audit_logs"]',
    'system',
    '["GDPR", "CCPA"]'
),
(
    gen_random_uuid(),
    'Remove Sensitive User Data',
    'ssn',
    'remove',
    NULL,
    '["users", "compliance_report"]',
    'system',
    '["HIPAA", "GDPR"]'
),
(
    gen_random_uuid(),
    'Anonymize IP Addresses',
    'ip_address',
    'anonymize',
    'XXX.XXX.XXX.XXX',
    '["audit_logs", "usage_analytics"]',
    'system',
    '["GDPR", "CCPA"]'
)
ON CONFLICT (rule_id) DO NOTHING;

-- Create performance indexes for large datasets
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epic17_exports_performance 
    ON epic17_export_requests (status, requested_at DESC, export_type) 
    WHERE requested_at >= NOW() - INTERVAL '30 days';

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epic17_files_active_downloads 
    ON epic17_export_output_files (status, download_count DESC, created_at DESC) 
    WHERE status = 'available';

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epic17_scheduled_next_runs 
    ON epic17_scheduled_exports (enabled, next_run_at ASC) 
    WHERE enabled = TRUE AND next_run_at > NOW();

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epic17_notifications_unhandled 
    ON epic17_export_notifications (notification_type, severity, acknowledged) 
    WHERE acknowledged = FALSE AND expires_at > NOW();

-- Create comprehensive export dashboard view
CREATE VIEW epic17_export_dashboard AS
SELECT 
    -- Current activity
    (SELECT COUNT(*) FROM epic17_export_requests WHERE status IN ('pending', 'queued', 'preparing', 'exporting', 'processing')) as active_exports,
    (SELECT COUNT(*) FROM epic17_export_requests WHERE requested_at >= NOW() - INTERVAL '24 hours') as exports_today,
    
    -- Success metrics (last 7 days)
    (SELECT COUNT(*) FROM epic17_export_requests WHERE status = 'completed' AND completed_at >= NOW() - INTERVAL '7 days') as completed_last_week,
    (SELECT COUNT(*) FROM epic17_export_requests WHERE status = 'failed' AND requested_at >= NOW() - INTERVAL '7 days') as failed_last_week,
    
    -- Performance metrics
    (SELECT AVG(execution_time) FROM epic17_export_requests WHERE status = 'completed' AND completed_at >= NOW() - INTERVAL '24 hours') as avg_execution_time_today,
    (SELECT SUM(file_size) FROM epic17_export_requests WHERE status = 'completed' AND completed_at >= NOW() - INTERVAL '24 hours') as data_exported_today,
    
    -- File management
    (SELECT COUNT(*) FROM epic17_export_output_files WHERE status = 'available') as available_files,
    (SELECT SUM(file_size) FROM epic17_export_output_files WHERE status = 'available') as total_available_file_size,
    
    -- Scheduled exports
    (SELECT COUNT(*) FROM epic17_scheduled_exports WHERE enabled = TRUE) as active_schedules,
    (SELECT COUNT(*) FROM epic17_scheduled_exports WHERE enabled = TRUE AND next_run_at <= NOW() + INTERVAL '1 hour') as due_soon_schedules,
    
    -- Templates and redaction
    (SELECT COUNT(*) FROM epic17_export_templates WHERE is_active = TRUE) as active_templates,
    (SELECT COUNT(*) FROM epic17_export_redaction_rules WHERE enabled = TRUE) as active_redaction_rules,
    
    -- Notifications
    (SELECT COUNT(*) FROM epic17_export_notifications WHERE acknowledged = FALSE AND expires_at > NOW()) as unacknowledged_notifications,
    (SELECT COUNT(*) FROM epic17_export_notifications WHERE notification_type = 'failure' AND sent_at >= NOW() - INTERVAL '24 hours') as failure_notifications_today;

-- Add table comments for documentation
COMMENT ON TABLE epic17_export_requests IS 'Export request tracking and management for Epic 17';
COMMENT ON TABLE epic17_export_output_files IS 'Output files generated by export operations';
COMMENT ON TABLE epic17_scheduled_exports IS 'Scheduled export automation and management';
COMMENT ON TABLE epic17_export_execution_history IS 'Export execution history and performance tracking';
COMMENT ON TABLE epic17_export_templates IS 'Pre-configured export templates for common use cases';
COMMENT ON TABLE epic17_export_redaction_rules IS 'Data redaction rules for compliance and security';
COMMENT ON TABLE epic17_export_notifications IS 'Export notifications and alerts management';
COMMENT ON TABLE epic17_export_performance_metrics IS 'Export system performance metrics and analytics';

-- Create triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_epic17_export_timestamp() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_epic17_export_requests_timestamp
    BEFORE UPDATE ON epic17_export_requests
    FOR EACH ROW EXECUTE FUNCTION update_epic17_export_timestamp();

CREATE TRIGGER update_epic17_scheduled_exports_timestamp
    BEFORE UPDATE ON epic17_scheduled_exports
    FOR EACH ROW EXECUTE FUNCTION update_epic17_export_timestamp();

CREATE TRIGGER update_epic17_export_templates_timestamp
    BEFORE UPDATE ON epic17_export_templates
    FOR EACH ROW EXECUTE FUNCTION update_epic17_export_timestamp();

CREATE TRIGGER update_epic17_export_redaction_rules_timestamp
    BEFORE UPDATE ON epic17_export_redaction_rules
    FOR EACH ROW EXECUTE FUNCTION update_epic17_export_timestamp();

-- Final setup completion message
DO $$
BEGIN
    RAISE NOTICE '✅ Epic 17 Export Functionality database schema created successfully';
    RAISE NOTICE '📊 Tables created: 8 core tables + 1 dashboard view';
    RAISE NOTICE '🔧 Functions created: 4 management functions + 1 cleanup function';
    RAISE NOTICE '📋 Templates: 4 default export templates configured';
    RAISE NOTICE '🛡️  Redaction: 4 default data redaction rules for compliance';
    RAISE NOTICE '⚡ Features: Multi-format export, scheduling, compliance, secure file handling';
    RAISE NOTICE '📈 Formats: JSON, CSV, XML, Excel, PDF, YAML, TSV support';
    RAISE NOTICE '🔒 Security: Data redaction, encryption, access controls, audit trails';
    RAISE NOTICE '📅 Automation: Scheduled exports, templates, notifications, performance tracking';
    RAISE NOTICE '🚀 Export system ready for Epic 17 API management';
END $$;