import { z } from 'zod';
export declare const ExportFormatSchema: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
export declare const TemplateTypeSchema: z.ZodEnum<["full", "summary", "diff", "custom"]>;
export declare const ExportTemplateSchema: z.ZodObject<{
    id: z.ZodString;
    project_id: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    export_format: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
    template_type: z.ZodEnum<["full", "summary", "diff", "custom"]>;
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    format_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    filter_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    template_content: z.ZodOptional<z.ZodString>;
    template_schema: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    created_by: z.ZodString;
    created_at: z.ZodString;
    updated_at: z.ZodString;
    is_public: z.ZodDefault<z.ZodBoolean>;
    is_system_template: z.ZodDefault<z.ZodBoolean>;
    usage_count: z.ZodDefault<z.ZodNumber>;
    last_used_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    created_at: string;
    usage_count: number;
    created_by: string;
    updated_at: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    template_type: "custom" | "summary" | "full" | "diff";
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    format_options: Record<string, unknown>;
    filter_options: Record<string, unknown>;
    is_public: boolean;
    is_system_template: boolean;
    description?: string | undefined;
    template_content?: string | undefined;
    template_schema?: Record<string, unknown> | undefined;
    last_used_at?: string | undefined;
}, {
    id: string;
    name: string;
    created_at: string;
    created_by: string;
    updated_at: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    template_type: "custom" | "summary" | "full" | "diff";
    description?: string | undefined;
    usage_count?: number | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    format_options?: Record<string, unknown> | undefined;
    filter_options?: Record<string, unknown> | undefined;
    template_content?: string | undefined;
    template_schema?: Record<string, unknown> | undefined;
    is_public?: boolean | undefined;
    is_system_template?: boolean | undefined;
    last_used_at?: string | undefined;
}>;
export declare const CreateExportTemplateSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    project_id: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    export_format: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
    template_type: z.ZodEnum<["full", "summary", "diff", "custom"]>;
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    format_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    filter_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    template_content: z.ZodOptional<z.ZodString>;
    template_schema: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    created_by: z.ZodString;
    created_at: z.ZodString;
    updated_at: z.ZodString;
    is_public: z.ZodDefault<z.ZodBoolean>;
    is_system_template: z.ZodDefault<z.ZodBoolean>;
    usage_count: z.ZodDefault<z.ZodNumber>;
    last_used_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "usage_count" | "updated_at" | "last_used_at">, "strip", z.ZodTypeAny, {
    name: string;
    created_by: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    template_type: "custom" | "summary" | "full" | "diff";
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    format_options: Record<string, unknown>;
    filter_options: Record<string, unknown>;
    is_public: boolean;
    is_system_template: boolean;
    description?: string | undefined;
    template_content?: string | undefined;
    template_schema?: Record<string, unknown> | undefined;
}, {
    name: string;
    created_by: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    template_type: "custom" | "summary" | "full" | "diff";
    description?: string | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    format_options?: Record<string, unknown> | undefined;
    filter_options?: Record<string, unknown> | undefined;
    template_content?: string | undefined;
    template_schema?: Record<string, unknown> | undefined;
    is_public?: boolean | undefined;
    is_system_template?: boolean | undefined;
}>;
export declare const UpdateExportTemplateSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    created_by: z.ZodOptional<z.ZodString>;
    export_format: z.ZodOptional<z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>>;
    project_id: z.ZodOptional<z.ZodString>;
    template_type: z.ZodOptional<z.ZodEnum<["full", "summary", "diff", "custom"]>>;
    include_metadata: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    include_attribution: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    include_history: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    include_branching: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    include_comments: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    include_attachments: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    format_options: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    filter_options: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    template_content: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    template_schema: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    is_public: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    is_system_template: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    description?: string | undefined;
    created_by?: string | undefined;
    export_format?: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml" | undefined;
    project_id?: string | undefined;
    template_type?: "custom" | "summary" | "full" | "diff" | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    format_options?: Record<string, unknown> | undefined;
    filter_options?: Record<string, unknown> | undefined;
    template_content?: string | undefined;
    template_schema?: Record<string, unknown> | undefined;
    is_public?: boolean | undefined;
    is_system_template?: boolean | undefined;
}, {
    name?: string | undefined;
    description?: string | undefined;
    created_by?: string | undefined;
    export_format?: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml" | undefined;
    project_id?: string | undefined;
    template_type?: "custom" | "summary" | "full" | "diff" | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    format_options?: Record<string, unknown> | undefined;
    filter_options?: Record<string, unknown> | undefined;
    template_content?: string | undefined;
    template_schema?: Record<string, unknown> | undefined;
    is_public?: boolean | undefined;
    is_system_template?: boolean | undefined;
}>;
export declare const ExportJobStatusSchema: z.ZodEnum<["pending", "processing", "completed", "failed", "cancelled"]>;
export declare const ExportTypeSchema: z.ZodEnum<["version", "branch", "comparison", "full_project"]>;
export declare const ExportJobSchema: z.ZodObject<{
    id: z.ZodString;
    project_id: z.ZodString;
    template_id: z.ZodOptional<z.ZodString>;
    export_format: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
    export_type: z.ZodEnum<["version", "branch", "comparison", "full_project"]>;
    export_scope: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    source_snapshot_id: z.ZodOptional<z.ZodString>;
    source_branch_id: z.ZodOptional<z.ZodString>;
    comparison_snapshot_id: z.ZodOptional<z.ZodString>;
    export_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    custom_filters: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    status: z.ZodDefault<z.ZodEnum<["pending", "processing", "completed", "failed", "cancelled"]>>;
    progress_percentage: z.ZodDefault<z.ZodNumber>;
    output_file_path: z.ZodOptional<z.ZodString>;
    output_file_size: z.ZodOptional<z.ZodNumber>;
    output_file_hash: z.ZodOptional<z.ZodString>;
    download_url: z.ZodOptional<z.ZodString>;
    expires_at: z.ZodOptional<z.ZodString>;
    initiated_by: z.ZodString;
    started_at: z.ZodString;
    completed_at: z.ZodOptional<z.ZodString>;
    error_message: z.ZodOptional<z.ZodString>;
    processing_log: z.ZodOptional<z.ZodString>;
    processing_duration: z.ZodOptional<z.ZodNumber>;
    memory_usage: z.ZodOptional<z.ZodNumber>;
    cpu_usage: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    id: string;
    status: "processing" | "pending" | "completed" | "failed" | "cancelled";
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    export_type: "version" | "branch" | "comparison" | "full_project";
    export_scope: Record<string, unknown>;
    export_options: Record<string, unknown>;
    custom_filters: Record<string, unknown>;
    progress_percentage: number;
    initiated_by: string;
    started_at: string;
    expires_at?: string | undefined;
    template_id?: string | undefined;
    download_url?: string | undefined;
    source_snapshot_id?: string | undefined;
    source_branch_id?: string | undefined;
    comparison_snapshot_id?: string | undefined;
    output_file_path?: string | undefined;
    output_file_size?: number | undefined;
    output_file_hash?: string | undefined;
    completed_at?: string | undefined;
    error_message?: string | undefined;
    processing_log?: string | undefined;
    processing_duration?: number | undefined;
    memory_usage?: number | undefined;
    cpu_usage?: number | undefined;
}, {
    id: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    export_type: "version" | "branch" | "comparison" | "full_project";
    initiated_by: string;
    started_at: string;
    status?: "processing" | "pending" | "completed" | "failed" | "cancelled" | undefined;
    expires_at?: string | undefined;
    template_id?: string | undefined;
    download_url?: string | undefined;
    export_scope?: Record<string, unknown> | undefined;
    source_snapshot_id?: string | undefined;
    source_branch_id?: string | undefined;
    comparison_snapshot_id?: string | undefined;
    export_options?: Record<string, unknown> | undefined;
    custom_filters?: Record<string, unknown> | undefined;
    progress_percentage?: number | undefined;
    output_file_path?: string | undefined;
    output_file_size?: number | undefined;
    output_file_hash?: string | undefined;
    completed_at?: string | undefined;
    error_message?: string | undefined;
    processing_log?: string | undefined;
    processing_duration?: number | undefined;
    memory_usage?: number | undefined;
    cpu_usage?: number | undefined;
}>;
export declare const CreateExportJobSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    project_id: z.ZodString;
    template_id: z.ZodOptional<z.ZodString>;
    export_format: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
    export_type: z.ZodEnum<["version", "branch", "comparison", "full_project"]>;
    export_scope: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    source_snapshot_id: z.ZodOptional<z.ZodString>;
    source_branch_id: z.ZodOptional<z.ZodString>;
    comparison_snapshot_id: z.ZodOptional<z.ZodString>;
    export_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    custom_filters: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    status: z.ZodDefault<z.ZodEnum<["pending", "processing", "completed", "failed", "cancelled"]>>;
    progress_percentage: z.ZodDefault<z.ZodNumber>;
    output_file_path: z.ZodOptional<z.ZodString>;
    output_file_size: z.ZodOptional<z.ZodNumber>;
    output_file_hash: z.ZodOptional<z.ZodString>;
    download_url: z.ZodOptional<z.ZodString>;
    expires_at: z.ZodOptional<z.ZodString>;
    initiated_by: z.ZodString;
    started_at: z.ZodString;
    completed_at: z.ZodOptional<z.ZodString>;
    error_message: z.ZodOptional<z.ZodString>;
    processing_log: z.ZodOptional<z.ZodString>;
    processing_duration: z.ZodOptional<z.ZodNumber>;
    memory_usage: z.ZodOptional<z.ZodNumber>;
    cpu_usage: z.ZodOptional<z.ZodNumber>;
}, "id" | "status" | "download_url" | "progress_percentage" | "output_file_path" | "output_file_size" | "output_file_hash" | "started_at" | "completed_at" | "error_message" | "processing_log" | "processing_duration" | "memory_usage" | "cpu_usage">, "strip", z.ZodTypeAny, {
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    export_type: "version" | "branch" | "comparison" | "full_project";
    export_scope: Record<string, unknown>;
    export_options: Record<string, unknown>;
    custom_filters: Record<string, unknown>;
    initiated_by: string;
    expires_at?: string | undefined;
    template_id?: string | undefined;
    source_snapshot_id?: string | undefined;
    source_branch_id?: string | undefined;
    comparison_snapshot_id?: string | undefined;
}, {
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    export_type: "version" | "branch" | "comparison" | "full_project";
    initiated_by: string;
    expires_at?: string | undefined;
    template_id?: string | undefined;
    export_scope?: Record<string, unknown> | undefined;
    source_snapshot_id?: string | undefined;
    source_branch_id?: string | undefined;
    comparison_snapshot_id?: string | undefined;
    export_options?: Record<string, unknown> | undefined;
    custom_filters?: Record<string, unknown> | undefined;
}>;
export declare const UpdateExportJobSchema: z.ZodObject<{
    status: z.ZodOptional<z.ZodEnum<["pending", "processing", "completed", "failed", "cancelled"]>>;
    progress_percentage: z.ZodOptional<z.ZodNumber>;
    output_file_path: z.ZodOptional<z.ZodString>;
    output_file_size: z.ZodOptional<z.ZodNumber>;
    output_file_hash: z.ZodOptional<z.ZodString>;
    download_url: z.ZodOptional<z.ZodString>;
    expires_at: z.ZodOptional<z.ZodString>;
    completed_at: z.ZodOptional<z.ZodString>;
    error_message: z.ZodOptional<z.ZodString>;
    processing_log: z.ZodOptional<z.ZodString>;
    processing_duration: z.ZodOptional<z.ZodNumber>;
    memory_usage: z.ZodOptional<z.ZodNumber>;
    cpu_usage: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    status?: "processing" | "pending" | "completed" | "failed" | "cancelled" | undefined;
    expires_at?: string | undefined;
    download_url?: string | undefined;
    progress_percentage?: number | undefined;
    output_file_path?: string | undefined;
    output_file_size?: number | undefined;
    output_file_hash?: string | undefined;
    completed_at?: string | undefined;
    error_message?: string | undefined;
    processing_log?: string | undefined;
    processing_duration?: number | undefined;
    memory_usage?: number | undefined;
    cpu_usage?: number | undefined;
}, {
    status?: "processing" | "pending" | "completed" | "failed" | "cancelled" | undefined;
    expires_at?: string | undefined;
    download_url?: string | undefined;
    progress_percentage?: number | undefined;
    output_file_path?: string | undefined;
    output_file_size?: number | undefined;
    output_file_hash?: string | undefined;
    completed_at?: string | undefined;
    error_message?: string | undefined;
    processing_log?: string | undefined;
    processing_duration?: number | undefined;
    memory_usage?: number | undefined;
    cpu_usage?: number | undefined;
}>;
export declare const ExportScheduleSchema: z.ZodObject<{
    id: z.ZodString;
    project_id: z.ZodString;
    template_id: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    is_enabled: z.ZodDefault<z.ZodBoolean>;
    schedule_expression: z.ZodString;
    timezone: z.ZodDefault<z.ZodString>;
    export_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    notification_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    created_by: z.ZodString;
    created_at: z.ZodString;
    updated_at: z.ZodString;
    last_run_at: z.ZodOptional<z.ZodString>;
    next_run_at: z.ZodOptional<z.ZodString>;
    total_runs: z.ZodDefault<z.ZodNumber>;
    successful_runs: z.ZodDefault<z.ZodNumber>;
    failed_runs: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    created_at: string;
    schedule_expression: string;
    created_by: string;
    updated_at: string;
    template_id: string;
    project_id: string;
    timezone: string;
    export_options: Record<string, unknown>;
    is_enabled: boolean;
    notification_options: Record<string, unknown>;
    total_runs: number;
    successful_runs: number;
    failed_runs: number;
    description?: string | undefined;
    next_run_at?: string | undefined;
    last_run_at?: string | undefined;
}, {
    id: string;
    name: string;
    created_at: string;
    schedule_expression: string;
    created_by: string;
    updated_at: string;
    template_id: string;
    project_id: string;
    description?: string | undefined;
    next_run_at?: string | undefined;
    last_run_at?: string | undefined;
    timezone?: string | undefined;
    export_options?: Record<string, unknown> | undefined;
    is_enabled?: boolean | undefined;
    notification_options?: Record<string, unknown> | undefined;
    total_runs?: number | undefined;
    successful_runs?: number | undefined;
    failed_runs?: number | undefined;
}>;
export declare const CreateExportScheduleSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    project_id: z.ZodString;
    template_id: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    is_enabled: z.ZodDefault<z.ZodBoolean>;
    schedule_expression: z.ZodString;
    timezone: z.ZodDefault<z.ZodString>;
    export_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    notification_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    created_by: z.ZodString;
    created_at: z.ZodString;
    updated_at: z.ZodString;
    last_run_at: z.ZodOptional<z.ZodString>;
    next_run_at: z.ZodOptional<z.ZodString>;
    total_runs: z.ZodDefault<z.ZodNumber>;
    successful_runs: z.ZodDefault<z.ZodNumber>;
    failed_runs: z.ZodDefault<z.ZodNumber>;
}, "id" | "created_at" | "next_run_at" | "last_run_at" | "updated_at" | "total_runs" | "successful_runs" | "failed_runs">, "strip", z.ZodTypeAny, {
    name: string;
    schedule_expression: string;
    created_by: string;
    template_id: string;
    project_id: string;
    timezone: string;
    export_options: Record<string, unknown>;
    is_enabled: boolean;
    notification_options: Record<string, unknown>;
    description?: string | undefined;
}, {
    name: string;
    schedule_expression: string;
    created_by: string;
    template_id: string;
    project_id: string;
    description?: string | undefined;
    timezone?: string | undefined;
    export_options?: Record<string, unknown> | undefined;
    is_enabled?: boolean | undefined;
    notification_options?: Record<string, unknown> | undefined;
}>;
export declare const UpdateExportScheduleSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    schedule_expression: z.ZodOptional<z.ZodString>;
    created_by: z.ZodOptional<z.ZodString>;
    template_id: z.ZodOptional<z.ZodString>;
    project_id: z.ZodOptional<z.ZodString>;
    timezone: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    export_options: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    is_enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    notification_options: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    description?: string | undefined;
    schedule_expression?: string | undefined;
    created_by?: string | undefined;
    template_id?: string | undefined;
    project_id?: string | undefined;
    timezone?: string | undefined;
    export_options?: Record<string, unknown> | undefined;
    is_enabled?: boolean | undefined;
    notification_options?: Record<string, unknown> | undefined;
}, {
    name?: string | undefined;
    description?: string | undefined;
    schedule_expression?: string | undefined;
    created_by?: string | undefined;
    template_id?: string | undefined;
    project_id?: string | undefined;
    timezone?: string | undefined;
    export_options?: Record<string, unknown> | undefined;
    is_enabled?: boolean | undefined;
    notification_options?: Record<string, unknown> | undefined;
}>;
export declare const ShareAccessLevelSchema: z.ZodEnum<["public", "password_protected", "private"]>;
export declare const ExportShareSchema: z.ZodObject<{
    id: z.ZodString;
    export_job_id: z.ZodString;
    share_token: z.ZodString;
    access_level: z.ZodDefault<z.ZodEnum<["public", "password_protected", "private"]>>;
    password: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    max_downloads: z.ZodOptional<z.ZodNumber>;
    download_count: z.ZodDefault<z.ZodNumber>;
    allowed_ips: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    allow_download: z.ZodDefault<z.ZodBoolean>;
    allow_preview: z.ZodDefault<z.ZodBoolean>;
    track_access: z.ZodDefault<z.ZodBoolean>;
    notify_on_access: z.ZodDefault<z.ZodBoolean>;
    created_by: z.ZodString;
    created_at: z.ZodString;
    expires_at: z.ZodOptional<z.ZodString>;
    expires_in_days: z.ZodOptional<z.ZodNumber>;
    is_active: z.ZodDefault<z.ZodBoolean>;
    last_accessed_at: z.ZodOptional<z.ZodString>;
    access_count: z.ZodDefault<z.ZodNumber>;
    share_url: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    created_at: string;
    is_active: boolean;
    created_by: string;
    export_job_id: string;
    share_token: string;
    access_level: "private" | "public" | "password_protected";
    download_count: number;
    allowed_ips: string[];
    allow_download: boolean;
    allow_preview: boolean;
    track_access: boolean;
    notify_on_access: boolean;
    access_count: number;
    description?: string | undefined;
    password?: string | undefined;
    expires_at?: string | undefined;
    max_downloads?: number | undefined;
    expires_in_days?: number | undefined;
    last_accessed_at?: string | undefined;
    share_url?: string | undefined;
}, {
    id: string;
    created_at: string;
    created_by: string;
    export_job_id: string;
    share_token: string;
    description?: string | undefined;
    password?: string | undefined;
    expires_at?: string | undefined;
    is_active?: boolean | undefined;
    access_level?: "private" | "public" | "password_protected" | undefined;
    max_downloads?: number | undefined;
    download_count?: number | undefined;
    allowed_ips?: string[] | undefined;
    allow_download?: boolean | undefined;
    allow_preview?: boolean | undefined;
    track_access?: boolean | undefined;
    notify_on_access?: boolean | undefined;
    expires_in_days?: number | undefined;
    last_accessed_at?: string | undefined;
    access_count?: number | undefined;
    share_url?: string | undefined;
}>;
export declare const CreateExportShareSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    export_job_id: z.ZodString;
    share_token: z.ZodString;
    access_level: z.ZodDefault<z.ZodEnum<["public", "password_protected", "private"]>>;
    password: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    max_downloads: z.ZodOptional<z.ZodNumber>;
    download_count: z.ZodDefault<z.ZodNumber>;
    allowed_ips: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    allow_download: z.ZodDefault<z.ZodBoolean>;
    allow_preview: z.ZodDefault<z.ZodBoolean>;
    track_access: z.ZodDefault<z.ZodBoolean>;
    notify_on_access: z.ZodDefault<z.ZodBoolean>;
    created_by: z.ZodString;
    created_at: z.ZodString;
    expires_at: z.ZodOptional<z.ZodString>;
    expires_in_days: z.ZodOptional<z.ZodNumber>;
    is_active: z.ZodDefault<z.ZodBoolean>;
    last_accessed_at: z.ZodOptional<z.ZodString>;
    access_count: z.ZodDefault<z.ZodNumber>;
    share_url: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "download_count" | "last_accessed_at" | "access_count">, "strip", z.ZodTypeAny, {
    is_active: boolean;
    created_by: string;
    export_job_id: string;
    share_token: string;
    access_level: "private" | "public" | "password_protected";
    allowed_ips: string[];
    allow_download: boolean;
    allow_preview: boolean;
    track_access: boolean;
    notify_on_access: boolean;
    description?: string | undefined;
    password?: string | undefined;
    expires_at?: string | undefined;
    max_downloads?: number | undefined;
    expires_in_days?: number | undefined;
    share_url?: string | undefined;
}, {
    created_by: string;
    export_job_id: string;
    share_token: string;
    description?: string | undefined;
    password?: string | undefined;
    expires_at?: string | undefined;
    is_active?: boolean | undefined;
    access_level?: "private" | "public" | "password_protected" | undefined;
    max_downloads?: number | undefined;
    allowed_ips?: string[] | undefined;
    allow_download?: boolean | undefined;
    allow_preview?: boolean | undefined;
    track_access?: boolean | undefined;
    notify_on_access?: boolean | undefined;
    expires_in_days?: number | undefined;
    share_url?: string | undefined;
}>;
export declare const UpdateExportShareSchema: z.ZodObject<{
    share_name: z.ZodOptional<z.ZodString>;
    password_protected: z.ZodOptional<z.ZodBoolean>;
    password_hash: z.ZodOptional<z.ZodString>;
    allowed_downloads: z.ZodOptional<z.ZodNumber>;
    allowed_ips: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    expires_at: z.ZodOptional<z.ZodString>;
    is_active: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    expires_at?: string | undefined;
    is_active?: boolean | undefined;
    password_protected?: boolean | undefined;
    allowed_ips?: string[] | undefined;
    share_name?: string | undefined;
    password_hash?: string | undefined;
    allowed_downloads?: number | undefined;
}, {
    expires_at?: string | undefined;
    is_active?: boolean | undefined;
    password_protected?: boolean | undefined;
    allowed_ips?: string[] | undefined;
    share_name?: string | undefined;
    password_hash?: string | undefined;
    allowed_downloads?: number | undefined;
}>;
export declare const ExportAnalyticsSchema: z.ZodObject<{
    id: z.ZodString;
    project_id: z.ZodString;
    export_job_id: z.ZodOptional<z.ZodString>;
    template_id: z.ZodOptional<z.ZodString>;
    export_format: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
    export_size: z.ZodOptional<z.ZodNumber>;
    processing_time: z.ZodOptional<z.ZodNumber>;
    download_count: z.ZodDefault<z.ZodNumber>;
    user_id: z.ZodOptional<z.ZodString>;
    user_agent: z.ZodOptional<z.ZodString>;
    ip_address: z.ZodOptional<z.ZodString>;
    exported_at: z.ZodString;
    date_bucket: z.ZodString;
    hour_bucket: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    download_count: number;
    exported_at: string;
    date_bucket: string;
    hour_bucket: string;
    user_id?: string | undefined;
    template_id?: string | undefined;
    user_agent?: string | undefined;
    ip_address?: string | undefined;
    export_job_id?: string | undefined;
    export_size?: number | undefined;
    processing_time?: number | undefined;
}, {
    id: string;
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    exported_at: string;
    date_bucket: string;
    hour_bucket: string;
    user_id?: string | undefined;
    template_id?: string | undefined;
    user_agent?: string | undefined;
    ip_address?: string | undefined;
    export_job_id?: string | undefined;
    download_count?: number | undefined;
    export_size?: number | undefined;
    processing_time?: number | undefined;
}>;
export declare const CreateExportAnalyticsSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    project_id: z.ZodString;
    export_job_id: z.ZodOptional<z.ZodString>;
    template_id: z.ZodOptional<z.ZodString>;
    export_format: z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>;
    export_size: z.ZodOptional<z.ZodNumber>;
    processing_time: z.ZodOptional<z.ZodNumber>;
    download_count: z.ZodDefault<z.ZodNumber>;
    user_id: z.ZodOptional<z.ZodString>;
    user_agent: z.ZodOptional<z.ZodString>;
    ip_address: z.ZodOptional<z.ZodString>;
    exported_at: z.ZodString;
    date_bucket: z.ZodString;
    hour_bucket: z.ZodString;
}, "id" | "exported_at" | "date_bucket" | "hour_bucket">, "strip", z.ZodTypeAny, {
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    download_count: number;
    user_id?: string | undefined;
    template_id?: string | undefined;
    user_agent?: string | undefined;
    ip_address?: string | undefined;
    export_job_id?: string | undefined;
    export_size?: number | undefined;
    processing_time?: number | undefined;
}, {
    export_format: "json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml";
    project_id: string;
    user_id?: string | undefined;
    template_id?: string | undefined;
    user_agent?: string | undefined;
    ip_address?: string | undefined;
    export_job_id?: string | undefined;
    download_count?: number | undefined;
    export_size?: number | undefined;
    processing_time?: number | undefined;
}>;
export declare const ExportFormatDefinitionSchema: z.ZodObject<{
    id: z.ZodString;
    format_name: z.ZodString;
    display_name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    file_extension: z.ZodString;
    mime_type: z.ZodString;
    supports_metadata: z.ZodDefault<z.ZodBoolean>;
    supports_binary_data: z.ZodDefault<z.ZodBoolean>;
    supports_compression: z.ZodDefault<z.ZodBoolean>;
    supports_encryption: z.ZodDefault<z.ZodBoolean>;
    max_file_size: z.ZodOptional<z.ZodNumber>;
    default_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    validation_schema: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    is_enabled: z.ZodDefault<z.ZodBoolean>;
    is_system_format: z.ZodDefault<z.ZodBoolean>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "strip", z.ZodTypeAny, {
    id: string;
    created_at: string;
    updated_at: string;
    is_enabled: boolean;
    format_name: string;
    display_name: string;
    file_extension: string;
    mime_type: string;
    supports_metadata: boolean;
    supports_binary_data: boolean;
    supports_compression: boolean;
    supports_encryption: boolean;
    default_options: Record<string, unknown>;
    is_system_format: boolean;
    description?: string | undefined;
    max_file_size?: number | undefined;
    validation_schema?: Record<string, unknown> | undefined;
}, {
    id: string;
    created_at: string;
    updated_at: string;
    format_name: string;
    display_name: string;
    file_extension: string;
    mime_type: string;
    description?: string | undefined;
    is_enabled?: boolean | undefined;
    supports_metadata?: boolean | undefined;
    supports_binary_data?: boolean | undefined;
    supports_compression?: boolean | undefined;
    supports_encryption?: boolean | undefined;
    max_file_size?: number | undefined;
    default_options?: Record<string, unknown> | undefined;
    validation_schema?: Record<string, unknown> | undefined;
    is_system_format?: boolean | undefined;
}>;
export declare const CreateExportFormatDefinitionSchema: z.ZodObject<Omit<{
    id: z.ZodString;
    format_name: z.ZodString;
    display_name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    file_extension: z.ZodString;
    mime_type: z.ZodString;
    supports_metadata: z.ZodDefault<z.ZodBoolean>;
    supports_binary_data: z.ZodDefault<z.ZodBoolean>;
    supports_compression: z.ZodDefault<z.ZodBoolean>;
    supports_encryption: z.ZodDefault<z.ZodBoolean>;
    max_file_size: z.ZodOptional<z.ZodNumber>;
    default_options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    validation_schema: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    is_enabled: z.ZodDefault<z.ZodBoolean>;
    is_system_format: z.ZodDefault<z.ZodBoolean>;
    created_at: z.ZodString;
    updated_at: z.ZodString;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    is_enabled: boolean;
    format_name: string;
    display_name: string;
    file_extension: string;
    mime_type: string;
    supports_metadata: boolean;
    supports_binary_data: boolean;
    supports_compression: boolean;
    supports_encryption: boolean;
    default_options: Record<string, unknown>;
    is_system_format: boolean;
    description?: string | undefined;
    max_file_size?: number | undefined;
    validation_schema?: Record<string, unknown> | undefined;
}, {
    format_name: string;
    display_name: string;
    file_extension: string;
    mime_type: string;
    description?: string | undefined;
    is_enabled?: boolean | undefined;
    supports_metadata?: boolean | undefined;
    supports_binary_data?: boolean | undefined;
    supports_compression?: boolean | undefined;
    supports_encryption?: boolean | undefined;
    max_file_size?: number | undefined;
    default_options?: Record<string, unknown> | undefined;
    validation_schema?: Record<string, unknown> | undefined;
    is_system_format?: boolean | undefined;
}>;
export declare const UpdateExportFormatDefinitionSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    is_enabled: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    format_name: z.ZodOptional<z.ZodString>;
    display_name: z.ZodOptional<z.ZodString>;
    file_extension: z.ZodOptional<z.ZodString>;
    mime_type: z.ZodOptional<z.ZodString>;
    supports_metadata: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    supports_binary_data: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    supports_compression: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    supports_encryption: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    max_file_size: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    default_options: z.ZodOptional<z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    validation_schema: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    is_system_format: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    description?: string | undefined;
    is_enabled?: boolean | undefined;
    format_name?: string | undefined;
    display_name?: string | undefined;
    file_extension?: string | undefined;
    mime_type?: string | undefined;
    supports_metadata?: boolean | undefined;
    supports_binary_data?: boolean | undefined;
    supports_compression?: boolean | undefined;
    supports_encryption?: boolean | undefined;
    max_file_size?: number | undefined;
    default_options?: Record<string, unknown> | undefined;
    validation_schema?: Record<string, unknown> | undefined;
    is_system_format?: boolean | undefined;
}, {
    description?: string | undefined;
    is_enabled?: boolean | undefined;
    format_name?: string | undefined;
    display_name?: string | undefined;
    file_extension?: string | undefined;
    mime_type?: string | undefined;
    supports_metadata?: boolean | undefined;
    supports_binary_data?: boolean | undefined;
    supports_compression?: boolean | undefined;
    supports_encryption?: boolean | undefined;
    max_file_size?: number | undefined;
    default_options?: Record<string, unknown> | undefined;
    validation_schema?: Record<string, unknown> | undefined;
    is_system_format?: boolean | undefined;
}>;
export declare const CommonExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
}>;
export declare const JsonExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    pretty: z.ZodDefault<z.ZodBoolean>;
    include_schema: z.ZodDefault<z.ZodBoolean>;
    array_format: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    pretty: boolean;
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    include_schema: boolean;
    array_format: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    pretty?: boolean | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    include_schema?: boolean | undefined;
    array_format?: boolean | undefined;
}>;
export declare const YamlExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    include_comments: z.ZodDefault<z.ZodBoolean>;
    flow_style: z.ZodDefault<z.ZodBoolean>;
    explicit_start: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    flow_style: boolean;
    explicit_start: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    flow_style?: boolean | undefined;
    explicit_start?: boolean | undefined;
}>;
export declare const XmlExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    pretty: z.ZodDefault<z.ZodBoolean>;
    include_schema: z.ZodDefault<z.ZodBoolean>;
    namespace: z.ZodOptional<z.ZodString>;
    root_element: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    pretty: boolean;
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    include_schema: boolean;
    root_element: string;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
    namespace?: string | undefined;
}, {
    pretty?: boolean | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    include_schema?: boolean | undefined;
    namespace?: string | undefined;
    root_element?: string | undefined;
}>;
export declare const CsvExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    delimiter: z.ZodDefault<z.ZodString>;
    include_headers: z.ZodDefault<z.ZodBoolean>;
    quote_all: z.ZodDefault<z.ZodBoolean>;
    flatten_objects: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    delimiter: string;
    include_headers: boolean;
    quote_all: boolean;
    flatten_objects: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    delimiter?: string | undefined;
    include_headers?: boolean | undefined;
    quote_all?: boolean | undefined;
    flatten_objects?: boolean | undefined;
}>;
export declare const MarkdownExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    include_toc: z.ZodDefault<z.ZodBoolean>;
    format: z.ZodDefault<z.ZodEnum<["github", "commonmark"]>>;
    heading_level: z.ZodDefault<z.ZodNumber>;
    code_blocks: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    format: "github" | "commonmark";
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    include_toc: boolean;
    heading_level: number;
    code_blocks: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    format?: "github" | "commonmark" | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    include_toc?: boolean | undefined;
    heading_level?: number | undefined;
    code_blocks?: boolean | undefined;
}>;
export declare const PdfExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    page_size: z.ZodDefault<z.ZodEnum<["A4", "A3", "Letter", "Legal"]>>;
    orientation: z.ZodDefault<z.ZodEnum<["portrait", "landscape"]>>;
    include_images: z.ZodDefault<z.ZodBoolean>;
    font_size: z.ZodDefault<z.ZodNumber>;
    margins: z.ZodDefault<z.ZodObject<{,
        top: z.ZodDefault<z.ZodNumber>;
        right: z.ZodDefault<z.ZodNumber>;
        bottom: z.ZodDefault<z.ZodNumber>;
        left: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        top: number;
        bottom: number;
        left: number;
        right: number;
    }, {
        top?: number | undefined;
        bottom?: number | undefined;
        left?: number | undefined;
        right?: number | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    orientation: "portrait" | "landscape";
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    page_size: "A4" | "A3" | "Letter" | "Legal";
    include_images: boolean;
    font_size: number;
    margins: {
        top: number;
        bottom: number;
        left: number;
        right: number;
    };
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    orientation?: "portrait" | "landscape" | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    page_size?: "A4" | "A3" | "Letter" | "Legal" | undefined;
    include_images?: boolean | undefined;
    font_size?: number | undefined;
    margins?: {
        top?: number | undefined;
        bottom?: number | undefined;
        left?: number | undefined;
        right?: number | undefined;
    } | undefined;
}>;
export declare const HtmlExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    include_css: z.ZodDefault<z.ZodBoolean>;
    standalone: z.ZodDefault<z.ZodBoolean>;
    theme: z.ZodDefault<z.ZodEnum<["default", "dark", "light"]>>;
    minify: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    theme: "default" | "light" | "dark";
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    include_css: boolean;
    standalone: boolean;
    minify: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    theme?: "default" | "light" | "dark" | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    include_css?: boolean | undefined;
    standalone?: boolean | undefined;
    minify?: boolean | undefined;
}>;
export declare const ZipExportOptionsSchema: z.ZodObject<{
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    compression_level: z.ZodDefault<z.ZodNumber>;
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    separate_files: z.ZodDefault<z.ZodBoolean>;
    folder_structure: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    compression_level: number;
    separate_files: boolean;
    folder_structure: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    compression_level?: number | undefined;
    separate_files?: boolean | undefined;
    folder_structure?: boolean | undefined;
}>;
export declare const VFXExportOptionsSchema: z.ZodObject<{
    include_metadata: z.ZodDefault<z.ZodBoolean>;
    include_attribution: z.ZodDefault<z.ZodBoolean>;
    include_history: z.ZodDefault<z.ZodBoolean>;
    include_branching: z.ZodDefault<z.ZodBoolean>;
    include_comments: z.ZodDefault<z.ZodBoolean>;
    include_attachments: z.ZodDefault<z.ZodBoolean>;
    date_range: z.ZodOptional<z.ZodObject<{,
        start: z.ZodOptional<z.ZodString>;
        end: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        start?: string | undefined;
        end?: string | undefined;
    }, {
        start?: string | undefined;
        end?: string | undefined;
    }>>;
    user_filters: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    compress_output: z.ZodDefault<z.ZodBoolean>;
    encrypt_output: z.ZodDefault<z.ZodBoolean>;
    encryption_key: z.ZodOptional<z.ZodString>;
} & {
    quality: z.ZodDefault<z.ZodEnum<["production", "preview", "debug"]>>;
    include_debug_info: z.ZodDefault<z.ZodBoolean>;
    include_historical_data: z.ZodDefault<z.ZodBoolean>;
    include_performance_data: z.ZodDefault<z.ZodBoolean>;
    include_variant_data: z.ZodDefault<z.ZodBoolean>;
    enable_controlnet_support: z.ZodDefault<z.ZodBoolean>;
    enable_animation_framework: z.ZodDefault<z.ZodBoolean>;
    include_rendering_data: z.ZodDefault<z.ZodBoolean>;
    include_camera_data: z.ZodDefault<z.ZodBoolean>;
    include_lighting_data: z.ZodDefault<z.ZodBoolean>;
    include_ecosystem_data: z.ZodDefault<z.ZodBoolean>;
    format_version: z.ZodDefault<z.ZodString>;
    backwards_compatible: z.ZodDefault<z.ZodBoolean>;
    include_reproducibility_data: z.ZodDefault<z.ZodBoolean>;
    exact_reproduction: z.ZodDefault<z.ZodBoolean>;
    preserve_node_configuration: z.ZodDefault<z.ZodBoolean>;
    include_rng_states: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    quality: "debug" | "preview" | "production";
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    include_debug_info: boolean;
    include_historical_data: boolean;
    include_performance_data: boolean;
    include_variant_data: boolean;
    enable_controlnet_support: boolean;
    enable_animation_framework: boolean;
    include_rendering_data: boolean;
    include_camera_data: boolean;
    include_lighting_data: boolean;
    include_ecosystem_data: boolean;
    format_version: string;
    backwards_compatible: boolean;
    include_reproducibility_data: boolean;
    exact_reproduction: boolean;
    preserve_node_configuration: boolean;
    include_rng_states: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}, {
    quality?: "debug" | "preview" | "production" | undefined;
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
    include_debug_info?: boolean | undefined;
    include_historical_data?: boolean | undefined;
    include_performance_data?: boolean | undefined;
    include_variant_data?: boolean | undefined;
    enable_controlnet_support?: boolean | undefined;
    enable_animation_framework?: boolean | undefined;
    include_rendering_data?: boolean | undefined;
    include_camera_data?: boolean | undefined;
    include_lighting_data?: boolean | undefined;
    include_ecosystem_data?: boolean | undefined;
    format_version?: string | undefined;
    backwards_compatible?: boolean | undefined;
    include_reproducibility_data?: boolean | undefined;
    exact_reproduction?: boolean | undefined;
    preserve_node_configuration?: boolean | undefined;
    include_rng_states?: boolean | undefined;
}>;
export declare const ExportResultSchema: z.ZodObject<{
    job_id: z.ZodString;
    status: z.ZodEnum<["pending", "processing", "completed", "failed", "cancelled"]>;
    download_url: z.ZodOptional<z.ZodString>;
    file_size: z.ZodOptional<z.ZodNumber>;
    expires_at: z.ZodOptional<z.ZodString>;
    share_token: z.ZodOptional<z.ZodString>;
    error_message: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "processing" | "pending" | "completed" | "failed" | "cancelled";
    job_id: string;
    expires_at?: string | undefined;
    download_url?: string | undefined;
    error_message?: string | undefined;
    share_token?: string | undefined;
    file_size?: number | undefined;
}, {
    status: "processing" | "pending" | "completed" | "failed" | "cancelled";
    job_id: string;
    expires_at?: string | undefined;
    download_url?: string | undefined;
    error_message?: string | undefined;
    share_token?: string | undefined;
    file_size?: number | undefined;
}>;
export declare const ExportProgressSchema: z.ZodObject<{
    job_id: z.ZodString;
    status: z.ZodEnum<["pending", "processing", "completed", "failed", "cancelled"]>;
    progress_percentage: z.ZodNumber;
    current_step: z.ZodOptional<z.ZodString>;
    estimated_completion: z.ZodOptional<z.ZodString>;
    processing_log: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "processing" | "pending" | "completed" | "failed" | "cancelled";
    progress_percentage: number;
    job_id: string;
    processing_log?: string | undefined;
    current_step?: string | undefined;
    estimated_completion?: string | undefined;
}, {
    status: "processing" | "pending" | "completed" | "failed" | "cancelled";
    progress_percentage: number;
    job_id: string;
    processing_log?: string | undefined;
    current_step?: string | undefined;
    estimated_completion?: string | undefined;
}>;
export declare const ExportStatisticsSchema: z.ZodObject<{
    project_id: z.ZodString;
    total_exports: z.ZodNumber;
    exports_by_format: z.ZodRecord<z.ZodEnum<["json", "yaml", "xml", "csv", "markdown", "pdf", "html", "zip", "vfx"]>, z.ZodNumber>;
    exports_by_type: z.ZodRecord<z.ZodEnum<["version", "branch", "comparison", "full_project"]>, z.ZodNumber>;
    total_size: z.ZodNumber;
    average_processing_time: z.ZodNumber;
    most_used_templates: z.ZodArray<z.ZodObject<{,
        template_id: z.ZodString;
        template_name: z.ZodString;
        usage_count: z.ZodNumber;
    }, "strip", z.ZodTypeAny, {
        usage_count: number;
        template_id: string;
        template_name: string;
    }, {
        usage_count: number;
        template_id: string;
        template_name: string;
    }>, "many">;
    success_rate: z.ZodNumber;
    last_export_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    project_id: string;
    total_exports: number;
    exports_by_format: Partial<Record<"json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml", number>>;
    exports_by_type: Partial<Record<"version" | "branch" | "comparison" | "full_project", number>>;
    total_size: number;
    average_processing_time: number;
    most_used_templates: {
        usage_count: number;
        template_id: string;
        template_name: string;
    }[];
    success_rate: number;
    last_export_at?: string | undefined;
}, {
    project_id: string;
    total_exports: number;
    exports_by_format: Partial<Record<"json" | "yaml" | "csv" | "markdown" | "html" | "vfx" | "zip" | "pdf" | "xml", number>>;
    exports_by_type: Partial<Record<"version" | "branch" | "comparison" | "full_project", number>>;
    total_size: number;
    average_processing_time: number;
    most_used_templates: {
        usage_count: number;
        template_id: string;
        template_name: string;
    }[];
    success_rate: number;
    last_export_at?: string | undefined;
}>;
export type ExportFormat = z.infer<typeof ExportFormatSchema>;
export type TemplateType = z.infer<typeof TemplateTypeSchema>;
export type ExportTemplate = z.infer<typeof ExportTemplateSchema>;
export type CreateExportTemplate = z.infer<typeof CreateExportTemplateSchema>;
export type UpdateExportTemplate = z.infer<typeof UpdateExportTemplateSchema>;
export type ExportJobStatus = z.infer<typeof ExportJobStatusSchema>;
export type ExportType = z.infer<typeof ExportTypeSchema>;
export type ExportJob = z.infer<typeof ExportJobSchema>;
export type CreateExportJob = z.infer<typeof CreateExportJobSchema>;
export type UpdateExportJob = z.infer<typeof UpdateExportJobSchema>;
export type ExportSchedule = z.infer<typeof ExportScheduleSchema>;
export type CreateExportSchedule = z.infer<typeof CreateExportScheduleSchema>;
export type UpdateExportSchedule = z.infer<typeof UpdateExportScheduleSchema>;
export type ExportShare = z.infer<typeof ExportShareSchema>;
export type CreateExportShare = z.infer<typeof CreateExportShareSchema>;
export type UpdateExportShare = z.infer<typeof UpdateExportShareSchema>;
export type ExportAnalytics = z.infer<typeof ExportAnalyticsSchema>;
export type CreateExportAnalytics = z.infer<typeof CreateExportAnalyticsSchema>;
export type ExportFormatDefinition = z.infer<typeof ExportFormatDefinitionSchema>;
export type CreateExportFormatDefinition = z.infer<typeof CreateExportFormatDefinitionSchema>;
export type UpdateExportFormatDefinition = z.infer<typeof UpdateExportFormatDefinitionSchema>;
export type CommonExportOptions = z.infer<typeof CommonExportOptionsSchema>;
export type JsonExportOptions = z.infer<typeof JsonExportOptionsSchema>;
export type YamlExportOptions = z.infer<typeof YamlExportOptionsSchema>;
export type XmlExportOptions = z.infer<typeof XmlExportOptionsSchema>;
export type CsvExportOptions = z.infer<typeof CsvExportOptionsSchema>;
export type MarkdownExportOptions = z.infer<typeof MarkdownExportOptionsSchema>;
export type PdfExportOptions = z.infer<typeof PdfExportOptionsSchema>;
export type HtmlExportOptions = z.infer<typeof HtmlExportOptionsSchema>;
export type ZipExportOptions = z.infer<typeof ZipExportOptionsSchema>;
export type VFXExportOptions = z.infer<typeof VFXExportOptionsSchema>;
export type ExportResult = z.infer<typeof ExportResultSchema>;
export type ExportProgress = z.infer<typeof ExportProgressSchema>;
export type ExportStatistics = z.infer<typeof ExportStatisticsSchema>;

export type ExportTemplateWithStats = ExportTemplate & {
    recent_jobs: ExportJob[];
    avg_processing_time: number;
    success_rate: number;
};

export type ExportJobWithTemplate = ExportJob & {
    template: ExportTemplate | null;
    share: ExportShare | null;
};

export type ExportScheduleWithStats = ExportSchedule & {
    template: ExportTemplate;
    recent_jobs: ExportJob[];
    next_scheduled_run: string;
};
export declare function validateExportOptions(format: ExportFormat, options: any): z.SafeParseSuccess<{
    include_metadata: boolean;
    include_attribution: boolean;
    include_history: boolean;
    include_branching: boolean;
    include_comments: boolean;
    include_attachments: boolean;
    compress_output: boolean;
    encrypt_output: boolean;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    encryption_key?: string | undefined;
}> | z.SafeParseError<{
    include_metadata?: boolean | undefined;
    include_attribution?: boolean | undefined;
    include_history?: boolean | undefined;
    include_branching?: boolean | undefined;
    include_comments?: boolean | undefined;
    include_attachments?: boolean | undefined;
    date_range?: {
        start?: string | undefined;
        end?: string | undefined;
    } | undefined;
    user_filters?: string[] | undefined;
    compress_output?: boolean | undefined;
    encrypt_output?: boolean | undefined;
    encryption_key?: string | undefined;
}>;
export declare export type ExportFormat = z.infer<typeof ExportFormatSchema>;
export type TemplateType = z.infer<typeof TemplateTypeSchema>;
export type ExportType = z.infer<typeof ExportTypeSchema>;
export type ExportJobStatus = z.infer<typeof ExportJobStatusSchema>;
export type ExportTemplate = z.infer<typeof ExportTemplateSchema>;
export type CreateExportTemplate = z.infer<typeof CreateExportTemplateSchema>;
export type UpdateExportTemplate = z.infer<typeof UpdateExportTemplateSchema>;
export type ExportJob = z.infer<typeof ExportJobSchema>;
export type CreateExportJob = z.infer<typeof CreateExportJobSchema>;
export type UpdateExportJob = z.infer<typeof UpdateExportJobSchema>;
export type ExportSchedule = z.infer<typeof ExportScheduleSchema>;
export type CreateExportSchedule = z.infer<typeof CreateExportScheduleSchema>;
export type UpdateExportSchedule = z.infer<typeof UpdateExportScheduleSchema>;
export type ExportShare = z.infer<typeof ExportShareSchema>;
export type CreateExportShare = z.infer<typeof CreateExportShareSchema>;
export type UpdateExportShare = z.infer<typeof UpdateExportShareSchema>;
export type ExportAnalytics = z.infer<typeof ExportAnalyticsSchema>;
export type CreateExportAnalytics = z.infer<typeof CreateExportAnalyticsSchema>;
export type ExportFormatDefinition = z.infer<typeof ExportFormatDefinitionSchema>;
export type CreateExportFormatDefinition = z.infer<typeof CreateExportFormatDefinitionSchema>;
export type UpdateExportFormatDefinition = z.infer<typeof UpdateExportFormatDefinitionSchema>;
export type CommonExportOptions = z.infer<typeof CommonExportOptionsSchema>;
export type JsonExportOptions = z.infer<typeof JsonExportOptionsSchema>;
export type YamlExportOptions = z.infer<typeof YamlExportOptionsSchema>;
export type XmlExportOptions = z.infer<typeof XmlExportOptionsSchema>;
export type CsvExportOptions = z.infer<typeof CsvExportOptionsSchema>;
export type MarkdownExportOptions = z.infer<typeof MarkdownExportOptionsSchema>;
export type PdfExportOptions = z.infer<typeof PdfExportOptionsSchema>;
export type HtmlExportOptions = z.infer<typeof HtmlExportOptionsSchema>;
export type ZipExportOptions = z.infer<typeof ZipExportOptionsSchema>;
export type ExportStatistics = z.infer<typeof ExportStatisticsSchema>;
//# sourceMappingURL=export.d.ts.map