/**
 * Epic 16 Feedback System Data Model
 * Task: E16-1753114247084-CE7C08 - Create feedback system
 *
 * Comprehensive feedback system for all contribution types including
 * ratings, reviews, comments, reports, and moderation workflows.
 */
import { z } from 'zod';
export declare const FeedbackTypeSchema: z.ZodEnum<["rating", "review", "comment", "report", "suggestion", "bug_report", "feature_request"]>;
export declare const FeedbackStatusSchema: z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>;
export declare const ReportReasonSchema: z.ZodEnum<["inappropriate_content", "spam", "copyright_violation", "offensive_language", "misleading_information", "low_quality", "duplicate_content", "terms_violation", "other"]>;
export declare const FeedbackCategorySchema: z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>;
export declare const BaseFeedbackSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodEnum<["rating", "review", "comment", "report", "suggestion", "bug_report", "feature_request"]>;
    category: z.ZodDefault<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    targetType: z.ZodEnum<["contribution", "template", "user", "platform"]>;
    targetId: z.ZodString;
    authorId: z.ZodString;
    authorName: z.ZodString;
    authorVerified: z.ZodDefault<z.ZodBoolean>;
    isAnonymous: z.ZodDefault<z.ZodBoolean>;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    attachments: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["image", "video", "document", "screenshot"]>;
        url: z.ZodString;
        filename: z.ZodString;
        size: z.ZodNumber;
        mimeType: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }>, "many">>;
    rating: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>>;
    visibility: z.ZodDefault<z.ZodEnum<["public", "private", "moderated"]>>;
    helpfulVotes: z.ZodDefault<z.ZodNumber>;
    notHelpfulVotes: z.ZodDefault<z.ZodNumber>;
    replies: z.ZodDefault<z.ZodNumber>;
    moderatedBy: z.ZodOptional<z.ZodString>;
    moderatedAt: z.ZodOptional<z.ZodDate>;
    moderationNotes: z.ZodOptional<z.ZodString>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    resolvedAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged";
    type: "rating" | "comment" | "review" | "suggestion" | "report" | "feature_request" | "bug_report";
    category: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing";
    metadata: Record<string, unknown>;
    content: string;
    targetId: string;
    visibility: "private" | "public" | "moderated";
    targetType: "template" | "platform" | "user" | "contribution";
    helpfulVotes: number;
    authorId: string;
    authorName: string;
    replies: number;
    attachments: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[];
    authorVerified: boolean;
    isAnonymous: boolean;
    notHelpfulVotes: number;
    rating?: number | undefined;
    title?: string | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    moderationNotes?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: "rating" | "comment" | "review" | "suggestion" | "report" | "feature_request" | "bug_report";
    content: string;
    targetId: string;
    targetType: "template" | "platform" | "user" | "contribution";
    authorId: string;
    authorName: string;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    metadata?: Record<string, unknown> | undefined;
    rating?: number | undefined;
    title?: string | undefined;
    visibility?: "private" | "public" | "moderated" | undefined;
    helpfulVotes?: number | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    replies?: number | undefined;
    attachments?: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[] | undefined;
    authorVerified?: boolean | undefined;
    isAnonymous?: boolean | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    notHelpfulVotes?: number | undefined;
    moderationNotes?: string | undefined;
}>;
export declare const ReviewFeedbackSchema: z.ZodObject<{
    id: z.ZodString;
    category: z.ZodDefault<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    targetType: z.ZodEnum<["contribution", "template", "user", "platform"]>;
    targetId: z.ZodString;
    authorId: z.ZodString;
    authorName: z.ZodString;
    authorVerified: z.ZodDefault<z.ZodBoolean>;
    isAnonymous: z.ZodDefault<z.ZodBoolean>;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    attachments: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["image", "video", "document", "screenshot"]>;
        url: z.ZodString;
        filename: z.ZodString;
        size: z.ZodNumber;
        mimeType: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }>, "many">>;
    status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>>;
    visibility: z.ZodDefault<z.ZodEnum<["public", "private", "moderated"]>>;
    helpfulVotes: z.ZodDefault<z.ZodNumber>;
    notHelpfulVotes: z.ZodDefault<z.ZodNumber>;
    replies: z.ZodDefault<z.ZodNumber>;
    moderatedBy: z.ZodOptional<z.ZodString>;
    moderatedAt: z.ZodOptional<z.ZodDate>;
    moderationNotes: z.ZodOptional<z.ZodString>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    resolvedAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
} & {
    type: z.ZodLiteral<"review">;
    rating: z.ZodNumber;
    pros: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    cons: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    useCase: z.ZodOptional<z.ZodString>;
    difficultyRating: z.ZodOptional<z.ZodNumber>;
    wouldRecommend: z.ZodOptional<z.ZodBoolean>;
    verifiedPurchase: z.ZodDefault<z.ZodBoolean>;
    purchaseDate: z.ZodOptional<z.ZodDate>;
    templateUsage: z.ZodOptional<z.ZodObject<{
        timesUsed: z.ZodOptional<z.ZodNumber>;
        outputQuality: z.ZodOptional<z.ZodNumber>;
        easeOfUse: z.ZodOptional<z.ZodNumber>;
        valueForMoney: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        outputQuality?: number | undefined;
        easeOfUse?: number | undefined;
        valueForMoney?: number | undefined;
        timesUsed?: number | undefined;
    }, {
        outputQuality?: number | undefined;
        easeOfUse?: number | undefined;
        valueForMoney?: number | undefined;
        timesUsed?: number | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged";
    type: "review";
    category: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing";
    metadata: Record<string, unknown>;
    rating: number;
    content: string;
    targetId: string;
    visibility: "private" | "public" | "moderated";
    targetType: "template" | "platform" | "user" | "contribution";
    helpfulVotes: number;
    authorId: string;
    authorName: string;
    replies: number;
    attachments: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[];
    authorVerified: boolean;
    isAnonymous: boolean;
    verifiedPurchase: boolean;
    notHelpfulVotes: number;
    pros: string[];
    cons: string[];
    title?: string | undefined;
    purchaseDate?: Date | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    useCase?: string | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    moderationNotes?: string | undefined;
    difficultyRating?: number | undefined;
    wouldRecommend?: boolean | undefined;
    templateUsage?: {
        outputQuality?: number | undefined;
        easeOfUse?: number | undefined;
        valueForMoney?: number | undefined;
        timesUsed?: number | undefined;
    } | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: "review";
    rating: number;
    content: string;
    targetId: string;
    targetType: "template" | "platform" | "user" | "contribution";
    authorId: string;
    authorName: string;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    metadata?: Record<string, unknown> | undefined;
    title?: string | undefined;
    visibility?: "private" | "public" | "moderated" | undefined;
    purchaseDate?: Date | undefined;
    helpfulVotes?: number | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    useCase?: string | undefined;
    replies?: number | undefined;
    attachments?: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[] | undefined;
    authorVerified?: boolean | undefined;
    isAnonymous?: boolean | undefined;
    verifiedPurchase?: boolean | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    notHelpfulVotes?: number | undefined;
    moderationNotes?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    difficultyRating?: number | undefined;
    wouldRecommend?: boolean | undefined;
    templateUsage?: {
        outputQuality?: number | undefined;
        easeOfUse?: number | undefined;
        valueForMoney?: number | undefined;
        timesUsed?: number | undefined;
    } | undefined;
}>;
export declare const ReportFeedbackSchema: z.ZodObject<{
    id: z.ZodString;
    category: z.ZodDefault<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    targetType: z.ZodEnum<["contribution", "template", "user", "platform"]>;
    targetId: z.ZodString;
    authorId: z.ZodString;
    authorName: z.ZodString;
    authorVerified: z.ZodDefault<z.ZodBoolean>;
    isAnonymous: z.ZodDefault<z.ZodBoolean>;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    attachments: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["image", "video", "document", "screenshot"]>;
        url: z.ZodString;
        filename: z.ZodString;
        size: z.ZodNumber;
        mimeType: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }>, "many">>;
    rating: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>>;
    visibility: z.ZodDefault<z.ZodEnum<["public", "private", "moderated"]>>;
    helpfulVotes: z.ZodDefault<z.ZodNumber>;
    notHelpfulVotes: z.ZodDefault<z.ZodNumber>;
    replies: z.ZodDefault<z.ZodNumber>;
    moderatedBy: z.ZodOptional<z.ZodString>;
    moderatedAt: z.ZodOptional<z.ZodDate>;
    moderationNotes: z.ZodOptional<z.ZodString>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    resolvedAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
} & {
    type: z.ZodLiteral<"report">;
    reason: z.ZodEnum<["inappropriate_content", "spam", "copyright_violation", "offensive_language", "misleading_information", "low_quality", "duplicate_content", "terms_violation", "other"]>;
    severity: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    evidence: z.ZodDefault<z.ZodArray<z.ZodObject<{
        type: z.ZodEnum<["screenshot", "url", "text", "video"]>;
        content: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "text" | "video" | "url" | "screenshot";
        content: string;
        description?: string | undefined;
    }, {
        type: "text" | "video" | "url" | "screenshot";
        content: string;
        description?: string | undefined;
    }>, "many">>;
    investigatedBy: z.ZodOptional<z.ZodString>;
    investigatedAt: z.ZodOptional<z.ZodDate>;
    investigationNotes: z.ZodOptional<z.ZodString>;
    actionTaken: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged";
    type: "report";
    category: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing";
    metadata: Record<string, unknown>;
    content: string;
    severity: "low" | "medium" | "high" | "critical";
    targetId: string;
    reason: "other" | "inappropriate_content" | "copyright_violation" | "spam" | "low_quality" | "offensive_language" | "misleading_information" | "duplicate_content" | "terms_violation";
    visibility: "private" | "public" | "moderated";
    targetType: "template" | "platform" | "user" | "contribution";
    evidence: {
        type: "text" | "video" | "url" | "screenshot";
        content: string;
        description?: string | undefined;
    }[];
    helpfulVotes: number;
    authorId: string;
    authorName: string;
    replies: number;
    attachments: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[];
    authorVerified: boolean;
    isAnonymous: boolean;
    notHelpfulVotes: number;
    rating?: number | undefined;
    title?: string | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    investigationNotes?: string | undefined;
    actionTaken?: string | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    moderationNotes?: string | undefined;
    investigatedBy?: string | undefined;
    investigatedAt?: Date | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: "report";
    content: string;
    targetId: string;
    reason: "other" | "inappropriate_content" | "copyright_violation" | "spam" | "low_quality" | "offensive_language" | "misleading_information" | "duplicate_content" | "terms_violation";
    targetType: "template" | "platform" | "user" | "contribution";
    authorId: string;
    authorName: string;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    metadata?: Record<string, unknown> | undefined;
    rating?: number | undefined;
    title?: string | undefined;
    severity?: "low" | "medium" | "high" | "critical" | undefined;
    visibility?: "private" | "public" | "moderated" | undefined;
    evidence?: {
        type: "text" | "video" | "url" | "screenshot";
        content: string;
        description?: string | undefined;
    }[] | undefined;
    helpfulVotes?: number | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    replies?: number | undefined;
    attachments?: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[] | undefined;
    authorVerified?: boolean | undefined;
    isAnonymous?: boolean | undefined;
    investigationNotes?: string | undefined;
    actionTaken?: string | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    notHelpfulVotes?: number | undefined;
    moderationNotes?: string | undefined;
    investigatedBy?: string | undefined;
    investigatedAt?: Date | undefined;
}>;
export declare const BugReportFeedbackSchema: z.ZodObject<{
    id: z.ZodString;
    category: z.ZodDefault<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    targetType: z.ZodEnum<["contribution", "template", "user", "platform"]>;
    targetId: z.ZodString;
    authorId: z.ZodString;
    authorName: z.ZodString;
    authorVerified: z.ZodDefault<z.ZodBoolean>;
    isAnonymous: z.ZodDefault<z.ZodBoolean>;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    attachments: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["image", "video", "document", "screenshot"]>;
        url: z.ZodString;
        filename: z.ZodString;
        size: z.ZodNumber;
        mimeType: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }>, "many">>;
    rating: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>>;
    visibility: z.ZodDefault<z.ZodEnum<["public", "private", "moderated"]>>;
    helpfulVotes: z.ZodDefault<z.ZodNumber>;
    notHelpfulVotes: z.ZodDefault<z.ZodNumber>;
    replies: z.ZodDefault<z.ZodNumber>;
    moderatedBy: z.ZodOptional<z.ZodString>;
    moderatedAt: z.ZodOptional<z.ZodDate>;
    moderationNotes: z.ZodOptional<z.ZodString>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    resolvedAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
} & {
    type: z.ZodLiteral<"bug_report">;
    severity: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    priority: z.ZodDefault<z.ZodEnum<["low", "medium", "high", "urgent"]>>;
    reproducible: z.ZodDefault<z.ZodBoolean>;
    stepsToReproduce: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    expectedBehavior: z.ZodOptional<z.ZodString>;
    actualBehavior: z.ZodOptional<z.ZodString>;
    environment: z.ZodOptional<z.ZodObject<{
        browser: z.ZodOptional<z.ZodString>;
        os: z.ZodOptional<z.ZodString>;
        device: z.ZodOptional<z.ZodString>;
        version: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        version?: string | undefined;
        browser?: string | undefined;
        os?: string | undefined;
        device?: string | undefined;
    }, {
        version?: string | undefined;
        browser?: string | undefined;
        os?: string | undefined;
        device?: string | undefined;
    }>>;
    assignedTo: z.ZodOptional<z.ZodString>;
    estimatedEffort: z.ZodOptional<z.ZodNumber>;
    fixedAt: z.ZodOptional<z.ZodDate>;
    fixVersion: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    priority: "low" | "medium" | "high" | "urgent";
    status: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged";
    type: "bug_report";
    category: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing";
    metadata: Record<string, unknown>;
    content: string;
    severity: "low" | "medium" | "high" | "critical";
    targetId: string;
    visibility: "private" | "public" | "moderated";
    targetType: "template" | "platform" | "user" | "contribution";
    helpfulVotes: number;
    authorId: string;
    authorName: string;
    replies: number;
    attachments: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[];
    authorVerified: boolean;
    isAnonymous: boolean;
    notHelpfulVotes: number;
    reproducible: boolean;
    stepsToReproduce: string[];
    rating?: number | undefined;
    title?: string | undefined;
    environment?: {
        version?: string | undefined;
        browser?: string | undefined;
        os?: string | undefined;
        device?: string | undefined;
    } | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    assignedTo?: string | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    estimatedEffort?: number | undefined;
    moderationNotes?: string | undefined;
    expectedBehavior?: string | undefined;
    actualBehavior?: string | undefined;
    fixedAt?: Date | undefined;
    fixVersion?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: "bug_report";
    content: string;
    targetId: string;
    targetType: "template" | "platform" | "user" | "contribution";
    authorId: string;
    authorName: string;
    priority?: "low" | "medium" | "high" | "urgent" | undefined;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    metadata?: Record<string, unknown> | undefined;
    rating?: number | undefined;
    title?: string | undefined;
    environment?: {
        version?: string | undefined;
        browser?: string | undefined;
        os?: string | undefined;
        device?: string | undefined;
    } | undefined;
    severity?: "low" | "medium" | "high" | "critical" | undefined;
    visibility?: "private" | "public" | "moderated" | undefined;
    helpfulVotes?: number | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    replies?: number | undefined;
    assignedTo?: string | undefined;
    attachments?: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[] | undefined;
    authorVerified?: boolean | undefined;
    isAnonymous?: boolean | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    estimatedEffort?: number | undefined;
    notHelpfulVotes?: number | undefined;
    moderationNotes?: string | undefined;
    reproducible?: boolean | undefined;
    stepsToReproduce?: string[] | undefined;
    expectedBehavior?: string | undefined;
    actualBehavior?: string | undefined;
    fixedAt?: Date | undefined;
    fixVersion?: string | undefined;
}>;
export declare const SuggestionFeedbackSchema: z.ZodObject<{
    id: z.ZodString;
    category: z.ZodDefault<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    targetType: z.ZodEnum<["contribution", "template", "user", "platform"]>;
    targetId: z.ZodString;
    authorId: z.ZodString;
    authorName: z.ZodString;
    authorVerified: z.ZodDefault<z.ZodBoolean>;
    isAnonymous: z.ZodDefault<z.ZodBoolean>;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    attachments: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["image", "video", "document", "screenshot"]>;
        url: z.ZodString;
        filename: z.ZodString;
        size: z.ZodNumber;
        mimeType: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }, {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }>, "many">>;
    rating: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>>;
    visibility: z.ZodDefault<z.ZodEnum<["public", "private", "moderated"]>>;
    helpfulVotes: z.ZodDefault<z.ZodNumber>;
    notHelpfulVotes: z.ZodDefault<z.ZodNumber>;
    replies: z.ZodDefault<z.ZodNumber>;
    moderatedBy: z.ZodOptional<z.ZodString>;
    moderatedAt: z.ZodOptional<z.ZodDate>;
    moderationNotes: z.ZodOptional<z.ZodString>;
    rejectionReason: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    resolvedAt: z.ZodOptional<z.ZodDate>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
} & {
    type: z.ZodLiteral<"suggestion">;
    impact: z.ZodDefault<z.ZodEnum<["low", "medium", "high"]>>;
    effort: z.ZodDefault<z.ZodEnum<["small", "medium", "large"]>>;
    proposedSolution: z.ZodOptional<z.ZodString>;
    benefits: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    alternatives: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    implementationStatus: z.ZodDefault<z.ZodEnum<["pending", "in_progress", "completed", "rejected"]>>;
    implementedBy: z.ZodOptional<z.ZodString>;
    implementedAt: z.ZodOptional<z.ZodDate>;
    implementationNotes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged";
    type: "suggestion";
    category: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing";
    metadata: Record<string, unknown>;
    content: string;
    targetId: string;
    visibility: "private" | "public" | "moderated";
    targetType: "template" | "platform" | "user" | "contribution";
    alternatives: string[];
    helpfulVotes: number;
    impact: "low" | "medium" | "high";
    authorId: string;
    authorName: string;
    replies: number;
    attachments: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[];
    authorVerified: boolean;
    isAnonymous: boolean;
    effort: "small" | "medium" | "large";
    notHelpfulVotes: number;
    benefits: string[];
    implementationStatus: "pending" | "completed" | "rejected" | "in_progress";
    rating?: number | undefined;
    title?: string | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    implementedBy?: string | undefined;
    moderationNotes?: string | undefined;
    proposedSolution?: string | undefined;
    implementedAt?: Date | undefined;
    implementationNotes?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    type: "suggestion";
    content: string;
    targetId: string;
    targetType: "template" | "platform" | "user" | "contribution";
    authorId: string;
    authorName: string;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    metadata?: Record<string, unknown> | undefined;
    rating?: number | undefined;
    title?: string | undefined;
    visibility?: "private" | "public" | "moderated" | undefined;
    alternatives?: string[] | undefined;
    helpfulVotes?: number | undefined;
    impact?: "low" | "medium" | "high" | undefined;
    rejectionReason?: string | undefined;
    resolvedAt?: Date | undefined;
    replies?: number | undefined;
    attachments?: {
        id: string;
        type: "document" | "video" | "image" | "screenshot";
        url: string;
        size: number;
        filename: string;
        mimeType: string;
    }[] | undefined;
    authorVerified?: boolean | undefined;
    isAnonymous?: boolean | undefined;
    moderatedBy?: string | undefined;
    moderatedAt?: Date | undefined;
    effort?: "small" | "medium" | "large" | undefined;
    implementedBy?: string | undefined;
    notHelpfulVotes?: number | undefined;
    moderationNotes?: string | undefined;
    proposedSolution?: string | undefined;
    benefits?: string[] | undefined;
    implementationStatus?: "pending" | "completed" | "rejected" | "in_progress" | undefined;
    implementedAt?: Date | undefined;
    implementationNotes?: string | undefined;
}>;
export declare const FeedbackSummarySchema: z.ZodObject<{
    targetId: z.ZodString;
    targetType: z.ZodString;
    averageRating: z.ZodDefault<z.ZodNumber>;
    totalRatings: z.ZodDefault<z.ZodNumber>;
    ratingDistribution: z.ZodObject<{
        1: z.ZodDefault<z.ZodNumber>;
        2: z.ZodDefault<z.ZodNumber>;
        3: z.ZodDefault<z.ZodNumber>;
        4: z.ZodDefault<z.ZodNumber>;
        5: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        2: number;
        1: number;
        3: number;
        4: number;
        5: number;
    }, {
        2?: number | undefined;
        1?: number | undefined;
        3?: number | undefined;
        4?: number | undefined;
        5?: number | undefined;
    }>;
    totalReviews: z.ZodDefault<z.ZodNumber>;
    verifiedReviews: z.ZodDefault<z.ZodNumber>;
    averageDifficulty: z.ZodDefault<z.ZodNumber>;
    recommendationRate: z.ZodDefault<z.ZodNumber>;
    totalFeedback: z.ZodDefault<z.ZodNumber>;
    feedbackByType: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodNumber>>;
    feedbackByCategory: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodNumber>>;
    totalHelpfulVotes: z.ZodDefault<z.ZodNumber>;
    totalReplies: z.ZodDefault<z.ZodNumber>;
    qualityScore: z.ZodDefault<z.ZodNumber>;
    moderationRate: z.ZodDefault<z.ZodNumber>;
    lastUpdated: z.ZodDate;
    generatedAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    targetId: string;
    lastUpdated: Date;
    averageRating: number;
    targetType: string;
    generatedAt: Date;
    qualityScore: number;
    totalRatings: number;
    totalReplies: number;
    totalHelpfulVotes: number;
    moderationRate: number;
    totalReviews: number;
    ratingDistribution: {
        2: number;
        1: number;
        3: number;
        4: number;
        5: number;
    };
    verifiedReviews: number;
    averageDifficulty: number;
    recommendationRate: number;
    totalFeedback: number;
    feedbackByType: Record<string, number>;
    feedbackByCategory: Record<string, number>;
}, {
    targetId: string;
    lastUpdated: Date;
    targetType: string;
    generatedAt: Date;
    ratingDistribution: {
        2?: number | undefined;
        1?: number | undefined;
        3?: number | undefined;
        4?: number | undefined;
        5?: number | undefined;
    };
    averageRating?: number | undefined;
    qualityScore?: number | undefined;
    totalRatings?: number | undefined;
    totalReplies?: number | undefined;
    totalHelpfulVotes?: number | undefined;
    moderationRate?: number | undefined;
    totalReviews?: number | undefined;
    verifiedReviews?: number | undefined;
    averageDifficulty?: number | undefined;
    recommendationRate?: number | undefined;
    totalFeedback?: number | undefined;
    feedbackByType?: Record<string, number> | undefined;
    feedbackByCategory?: Record<string, number> | undefined;
}>;
export declare const FeedbackVoteSchema: z.ZodObject<{
    id: z.ZodString;
    feedbackId: z.ZodString;
    userId: z.ZodString;
    voteType: z.ZodEnum<["helpful", "not_helpful"]>;
    createdAt: z.ZodDate;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    userId: string;
    feedbackId: string;
    voteType: "helpful" | "not_helpful";
}, {
    id: string;
    createdAt: Date;
    userId: string;
    feedbackId: string;
    voteType: "helpful" | "not_helpful";
}>;
export declare const FeedbackReplySchema: z.ZodObject<{
    id: z.ZodString;
    feedbackId: z.ZodString;
    parentReplyId: z.ZodOptional<z.ZodString>;
    authorId: z.ZodString;
    authorName: z.ZodString;
    authorType: z.ZodEnum<["user", "creator", "moderator", "admin"]>;
    content: z.ZodString;
    attachments: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["image", "document"]>;
        url: z.ZodString;
        filename: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        type: "document" | "image";
        url: string;
        filename: string;
    }, {
        id: string;
        type: "document" | "image";
        url: string;
        filename: string;
    }>, "many">>;
    status: z.ZodDefault<z.ZodEnum<["visible", "hidden", "deleted"]>>;
    likes: z.ZodDefault<z.ZodNumber>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    editedAt: z.ZodOptional<z.ZodDate>;
}, "strip", z.ZodTypeAny, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: "hidden" | "visible" | "deleted";
    content: string;
    likes: number;
    authorId: string;
    authorName: string;
    attachments: {
        id: string;
        type: "document" | "image";
        url: string;
        filename: string;
    }[];
    authorType: "admin" | "user" | "creator" | "moderator";
    feedbackId: string;
    editedAt?: Date | undefined;
    parentReplyId?: string | undefined;
}, {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    content: string;
    authorId: string;
    authorName: string;
    authorType: "admin" | "user" | "creator" | "moderator";
    feedbackId: string;
    status?: "hidden" | "visible" | "deleted" | undefined;
    likes?: number | undefined;
    attachments?: {
        id: string;
        type: "document" | "image";
        url: string;
        filename: string;
    }[] | undefined;
    editedAt?: Date | undefined;
    parentReplyId?: string | undefined;
}>;
export declare const CreateFeedbackRequestSchema: z.ZodObject<{
    type: z.ZodEnum<["rating", "review", "comment", "report", "suggestion", "bug_report", "feature_request"]>;
    category: z.ZodDefault<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    targetType: z.ZodEnum<["contribution", "template", "user", "platform"]>;
    targetId: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodString;
    rating: z.ZodOptional<z.ZodNumber>;
    isAnonymous: z.ZodDefault<z.ZodBoolean>;
    pros: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    cons: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    useCase: z.ZodOptional<z.ZodString>;
    wouldRecommend: z.ZodOptional<z.ZodBoolean>;
    reason: z.ZodOptional<z.ZodEnum<["inappropriate_content", "spam", "copyright_violation", "offensive_language", "misleading_information", "low_quality", "duplicate_content", "terms_violation", "other"]>>;
    evidence: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    severity: z.ZodOptional<z.ZodEnum<["low", "medium", "high", "critical"]>>;
    stepsToReproduce: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    expectedBehavior: z.ZodOptional<z.ZodString>;
    actualBehavior: z.ZodOptional<z.ZodString>;
    attachments: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    type: "rating" | "comment" | "review" | "suggestion" | "report" | "feature_request" | "bug_report";
    category: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing";
    content: string;
    targetId: string;
    targetType: "template" | "platform" | "user" | "contribution";
    attachments: string[];
    isAnonymous: boolean;
    rating?: number | undefined;
    title?: string | undefined;
    severity?: "low" | "medium" | "high" | "critical" | undefined;
    reason?: "other" | "inappropriate_content" | "copyright_violation" | "spam" | "low_quality" | "offensive_language" | "misleading_information" | "duplicate_content" | "terms_violation" | undefined;
    evidence?: string[] | undefined;
    useCase?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    wouldRecommend?: boolean | undefined;
    stepsToReproduce?: string[] | undefined;
    expectedBehavior?: string | undefined;
    actualBehavior?: string | undefined;
}, {
    type: "rating" | "comment" | "review" | "suggestion" | "report" | "feature_request" | "bug_report";
    content: string;
    targetId: string;
    targetType: "template" | "platform" | "user" | "contribution";
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    rating?: number | undefined;
    title?: string | undefined;
    severity?: "low" | "medium" | "high" | "critical" | undefined;
    reason?: "other" | "inappropriate_content" | "copyright_violation" | "spam" | "low_quality" | "offensive_language" | "misleading_information" | "duplicate_content" | "terms_violation" | undefined;
    evidence?: string[] | undefined;
    useCase?: string | undefined;
    attachments?: string[] | undefined;
    isAnonymous?: boolean | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    wouldRecommend?: boolean | undefined;
    stepsToReproduce?: string[] | undefined;
    expectedBehavior?: string | undefined;
    actualBehavior?: string | undefined;
}>;
export declare const UpdateFeedbackRequestSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    content: z.ZodOptional<z.ZodString>;
    rating: z.ZodOptional<z.ZodNumber>;
    pros: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    cons: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    useCase: z.ZodOptional<z.ZodString>;
    wouldRecommend: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    rating?: number | undefined;
    title?: string | undefined;
    content?: string | undefined;
    useCase?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    wouldRecommend?: boolean | undefined;
}, {
    rating?: number | undefined;
    title?: string | undefined;
    content?: string | undefined;
    useCase?: string | undefined;
    pros?: string[] | undefined;
    cons?: string[] | undefined;
    wouldRecommend?: boolean | undefined;
}>;
export declare const FeedbackFilterSchema: z.ZodObject<{
    targetId: z.ZodOptional<z.ZodString>;
    targetType: z.ZodOptional<z.ZodEnum<["contribution", "template", "user", "platform"]>>;
    type: z.ZodOptional<z.ZodEnum<["rating", "review", "comment", "report", "suggestion", "bug_report", "feature_request"]>>;
    category: z.ZodOptional<z.ZodEnum<["general", "usability", "performance", "documentation", "pricing", "support", "technical", "content_quality"]>>;
    status: z.ZodOptional<z.ZodEnum<["pending", "approved", "rejected", "flagged", "archived", "resolved"]>>;
    authorId: z.ZodOptional<z.ZodString>;
    verifiedOnly: z.ZodOptional<z.ZodBoolean>;
    minRating: z.ZodOptional<z.ZodNumber>;
    maxRating: z.ZodOptional<z.ZodNumber>;
    hasAttachments: z.ZodOptional<z.ZodBoolean>;
    createdAfter: z.ZodOptional<z.ZodDate>;
    createdBefore: z.ZodOptional<z.ZodDate>;
    search: z.ZodOptional<z.ZodString>;
    sortBy: z.ZodDefault<z.ZodEnum<["created_at", "rating", "helpful_votes", "updated_at"]>>;
    sortOrder: z.ZodDefault<z.ZodEnum<["asc", "desc"]>>;
    limit: z.ZodDefault<z.ZodNumber>;
    offset: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    offset: number;
    sortBy: "rating" | "created_at" | "updated_at" | "helpful_votes";
    sortOrder: "asc" | "desc";
    search?: string | undefined;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    type?: "rating" | "comment" | "review" | "suggestion" | "report" | "feature_request" | "bug_report" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    targetId?: string | undefined;
    targetType?: "template" | "platform" | "user" | "contribution" | undefined;
    minRating?: number | undefined;
    createdAfter?: Date | undefined;
    createdBefore?: Date | undefined;
    authorId?: string | undefined;
    verifiedOnly?: boolean | undefined;
    maxRating?: number | undefined;
    hasAttachments?: boolean | undefined;
}, {
    search?: string | undefined;
    status?: "pending" | "approved" | "rejected" | "archived" | "resolved" | "flagged" | undefined;
    type?: "rating" | "comment" | "review" | "suggestion" | "report" | "feature_request" | "bug_report" | undefined;
    category?: "performance" | "general" | "technical" | "documentation" | "usability" | "support" | "content_quality" | "pricing" | undefined;
    limit?: number | undefined;
    offset?: number | undefined;
    sortBy?: "rating" | "created_at" | "updated_at" | "helpful_votes" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
    targetId?: string | undefined;
    targetType?: "template" | "platform" | "user" | "contribution" | undefined;
    minRating?: number | undefined;
    createdAfter?: Date | undefined;
    createdBefore?: Date | undefined;
    authorId?: string | undefined;
    verifiedOnly?: boolean | undefined;
    maxRating?: number | undefined;
    hasAttachments?: boolean | undefined;
}>;
export declare const ModerateFeedbackRequestSchema: z.ZodObject<{
    action: z.ZodEnum<["approve", "reject", "flag", "archive"]>;
    notes: z.ZodOptional<z.ZodString>;
    rejectionReason: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    action: "approve" | "reject" | "flag" | "archive";
    notes?: string | undefined;
    rejectionReason?: string | undefined;
}, {
    action: "approve" | "reject" | "flag" | "archive";
    notes?: string | undefined;
    rejectionReason?: string | undefined;
}>;
export type FeedbackType = z.infer<typeof FeedbackTypeSchema>;
export type FeedbackStatus = z.infer<typeof FeedbackStatusSchema>;
export type ReportReason = z.infer<typeof ReportReasonSchema>;
export type FeedbackCategory = z.infer<typeof FeedbackCategorySchema>;
export type BaseFeedback = z.infer<typeof BaseFeedbackSchema>;
export type ReviewFeedback = z.infer<typeof ReviewFeedbackSchema>;
export type ReportFeedback = z.infer<typeof ReportFeedbackSchema>;
export type BugReportFeedback = z.infer<typeof BugReportFeedbackSchema>;
export type SuggestionFeedback = z.infer<typeof SuggestionFeedbackSchema>;
export type Feedback = BaseFeedback | ReviewFeedback | ReportFeedback | BugReportFeedback | SuggestionFeedback;
export type FeedbackSummary = z.infer<typeof FeedbackSummarySchema>;
export type FeedbackVote = z.infer<typeof FeedbackVoteSchema>;
export type FeedbackReply = z.infer<typeof FeedbackReplySchema>;
export type CreateFeedbackRequest = z.infer<typeof CreateFeedbackRequestSchema>;
export type UpdateFeedbackRequest = z.infer<typeof UpdateFeedbackRequestSchema>;
export type FeedbackFilter = z.infer<typeof FeedbackFilterSchema>;
export type ModerateFeedbackRequest = z.infer<typeof ModerateFeedbackRequestSchema>;
export declare const validateFeedback: (feedback: unknown) => Feedback;
export declare const validateCreateFeedbackRequest: (request: unknown) => CreateFeedbackRequest;
export declare const validateUpdateFeedbackRequest: (request: unknown) => UpdateFeedbackRequest;
export declare const validateFeedbackFilter: (filter: unknown) => FeedbackFilter;
export declare const validateModerateFeedbackRequest: (request: unknown) => ModerateFeedbackRequest;
export declare const FEEDBACK_TYPE_DESCRIPTIONS: {
    readonly rating: "Simple star rating";
    readonly review: "Detailed review with rating";
    readonly comment: "General comment or discussion";
    readonly report: "Report inappropriate content";
    readonly suggestion: "Improvement suggestion";
    readonly bug_report: "Bug or technical issue";
    readonly feature_request: "Request for new features";
};
export declare const FEEDBACK_CATEGORY_DESCRIPTIONS: {
    readonly general: "General feedback";
    readonly usability: "User experience and interface";
    readonly performance: "Speed and performance issues";
    readonly documentation: "Documentation and help content";
    readonly pricing: "Pricing and billing";
    readonly support: "Customer support experience";
    readonly technical: "Technical issues and bugs";
    readonly content_quality: "Quality of content and templates";
};
export declare const REPORT_REASON_DESCRIPTIONS: {
    readonly inappropriate_content: "Content is inappropriate or offensive";
    readonly spam: "Spam or promotional content";
    readonly copyright_violation: "Copyright or intellectual property violation";
    readonly offensive_language: "Contains offensive or abusive language";
    readonly misleading_information: "Contains false or misleading information";
    readonly low_quality: "Low quality or poorly written content";
    readonly duplicate_content: "Duplicate or copied content";
    readonly terms_violation: "Violates terms of service";
    readonly other: "Other reason (specify in description)";
};
export declare const FEEDBACK_DEFAULTS: {
    readonly RATING_REQUIRED_TYPES: readonly ["rating", "review"];
    readonly MAX_ATTACHMENTS: 5;
    readonly MAX_ATTACHMENT_SIZE_MB: 10;
    readonly AUTO_APPROVE_THRESHOLD: 80;
    readonly FLAGGED_THRESHOLD: 3;
    readonly MODERATION_QUEUE_PRIORITY: {
        readonly critical: 1;
        readonly high: 2;
        readonly medium: 3;
        readonly low: 4;
    };
};
//# sourceMappingURL=feedback.d.ts.map